// 500 additional headline templates (200 positive, 200 negative, 100 neutral)
// Each uses the same {NAME}, {TICKER}, {PRODUCT}, {ACTION}, {BAD_OUTCOME}, {GOOD_OUTCOME}, {RIVAL} placeholders
// as the base HEADLINE_TEMPLATES in headlines.ts.
export interface HeadlineTemplate {
  text: string;
  sentiment: 'positive' | 'negative' | 'neutral';
  impactPercent: number;
  sourceOffset: number;
}

export const EXTRA_HEADLINE_TEMPLATES: HeadlineTemplate[] = [
  // ==================== POSITIVE (1-200) ====================
  { text: "{NAME} announces breakthrough in {PRODUCT}, sending shares to a 52-week high!", sentiment: 'positive', impactPercent: 0.36, sourceOffset: 0 },
  { text: "Wall Street cheers as {NAME} beats earnings expectations by a wide margin on {PRODUCT} sales.", sentiment: 'positive', impactPercent: 0.31, sourceOffset: 1 },
  { text: "{NAME} signs landmark deal to supply {PRODUCT} to a Fortune 500 client.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 2 },
  { text: "Influential analyst raises price target on {TICKER}, citing {PRODUCT} momentum.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 3 },
  { text: "{NAME} unveils next-generation {PRODUCT} at a packed launch event.", sentiment: 'positive', impactPercent: 0.33, sourceOffset: 4 },
  { text: "Insiders at {NAME} load up on {TICKER} shares ahead of major announcement.", sentiment: 'positive', impactPercent: 0.29, sourceOffset: 5 },
  { text: "{NAME} {GOOD_OUTCOME}, stunning industry observers.", sentiment: 'positive', impactPercent: 0.44, sourceOffset: 6 },
  { text: "Retail investors pile into {TICKER} after a viral post about {PRODUCT}.", sentiment: 'positive', impactPercent: 0.40, sourceOffset: 7 },
  { text: "{NAME} expands into 12 new countries with its flagship {PRODUCT}.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 8 },
  { text: "Regulators approve {NAME}'s {PRODUCT} ahead of schedule.", sentiment: 'positive', impactPercent: 0.34, sourceOffset: 9 },
  { text: "{NAME} wins 'Company of the Year' for its work on {PRODUCT}.", sentiment: 'positive', impactPercent: 0.20, sourceOffset: 0 },
  { text: "Hedge funds increase stakes in {TICKER} as {PRODUCT} adoption accelerates.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 1 },
  { text: "{NAME} reports record pre-orders for its upcoming {PRODUCT} launch.", sentiment: 'positive', impactPercent: 0.37, sourceOffset: 2 },
  { text: "A famous celebrity endorses {NAME}'s {PRODUCT} on live television.", sentiment: 'positive', impactPercent: 0.32, sourceOffset: 3 },
  { text: "{NAME} announces a stock buyback program, signaling confidence in {PRODUCT}.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 4 },
  { text: "Trade publication names {NAME}'s {PRODUCT} the best in its class.", sentiment: 'positive', impactPercent: 0.21, sourceOffset: 5 },
  { text: "{NAME} {GOOD_OUTCOME}, leaving competitors scrambling.", sentiment: 'positive', impactPercent: 0.43, sourceOffset: 6 },
  { text: "Government awards {NAME} a multi-year contract for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.30, sourceOffset: 7 },
  { text: "{TICKER} added to a major market index, triggering automatic buying.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 8 },
  { text: "{NAME} hits a production milestone for {PRODUCT}, easing supply concerns.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 9 },
  { text: "A top-rated podcast features {NAME}'s {PRODUCT} as a must-have.", sentiment: 'positive', impactPercent: 0.19, sourceOffset: 0 },
  { text: "{NAME} announces a partnership with a leading research university on {PRODUCT}.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 1 },
  { text: "Customer reviews for {NAME}'s {PRODUCT} hit a record 4.9 stars.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 2 },
  { text: "{NAME} reveals it will {ACTION}, exciting growth investors.", sentiment: 'positive', impactPercent: 0.35, sourceOffset: 3 },
  { text: "A sovereign wealth fund discloses a large position in {TICKER}.", sentiment: 'positive', impactPercent: 0.38, sourceOffset: 4 },
  { text: "{NAME} reports that {PRODUCT} margins improved significantly this quarter.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 5 },
  { text: "Industry survey ranks {NAME} as the most trusted brand for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.20, sourceOffset: 6 },
  { text: "{NAME} announces a dividend increase, rewarding long-term {TICKER} holders.", sentiment: 'positive', impactPercent: 0.18, sourceOffset: 7 },
  { text: "A major retailer agrees to stock {NAME}'s {PRODUCT} nationwide.", sentiment: 'positive', impactPercent: 0.29, sourceOffset: 8 },
  { text: "{NAME} {GOOD_OUTCOME}, prompting a wave of analyst upgrades.", sentiment: 'positive', impactPercent: 0.42, sourceOffset: 9 },
  { text: "Patent office grants {NAME} a key patent protecting {PRODUCT}.", sentiment: 'positive', impactPercent: 0.31, sourceOffset: 0 },
  { text: "{NAME} secures exclusive rights to a critical component of {PRODUCT}.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 1 },
  { text: "A prominent tech blogger calls {NAME}'s {PRODUCT} 'a game-changer.'", sentiment: 'positive', impactPercent: 0.33, sourceOffset: 2 },
  { text: "{NAME} announces it will {ACTION}, beating rival {RIVAL} to market.", sentiment: 'positive', impactPercent: 0.36, sourceOffset: 3 },
  { text: "Institutional investors increase their {TICKER} holdings by 15%.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 4 },
  { text: "{NAME} reports that {PRODUCT} demand outstripped supply this quarter.", sentiment: 'positive', impactPercent: 0.30, sourceOffset: 5 },
  { text: "A famous athlete signs an endorsement deal with {NAME} for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 6 },
  { text: "{NAME} opens a new flagship facility dedicated to {PRODUCT}.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 7 },
  { text: "Survey shows {NAME}'s {PRODUCT} has the highest customer loyalty in its sector.", sentiment: 'positive', impactPercent: 0.21, sourceOffset: 8 },
  { text: "{NAME} announces a strategic acquisition to boost {PRODUCT} capabilities.", sentiment: 'positive', impactPercent: 0.32, sourceOffset: 9 },
  { text: "A leading magazine features {NAME} on its cover for {PRODUCT} innovation.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 0 },
  { text: "{NAME} reveals that {PRODUCT} sales grew 60% year-over-year.", sentiment: 'positive', impactPercent: 0.34, sourceOffset: 1 },
  { text: "Options traders bet big on {TICKER} ahead of {PRODUCT} launch.", sentiment: 'positive', impactPercent: 0.29, sourceOffset: 2 },
  { text: "{NAME} announces it will {ACTION}, opening a new revenue stream.", sentiment: 'positive', impactPercent: 0.37, sourceOffset: 3 },
  { text: "A major pension fund adds {TICKER} to its core portfolio.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 4 },
  { text: "{NAME} reports zero defects in the latest {PRODUCT} batch.", sentiment: 'positive', impactPercent: 0.20, sourceOffset: 5 },
  { text: "Industry analysts raise their {TICKER} price targets across the board.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 6 },
  { text: "{NAME} {GOOD_OUTCOME}, triggering a short squeeze on {TICKER}.", sentiment: 'positive', impactPercent: 0.46, sourceOffset: 7 },
  { text: "A viral unboxing video of {NAME}'s {PRODUCT} hits 50 million views.", sentiment: 'positive', impactPercent: 0.35, sourceOffset: 8 },
  { text: "{NAME} announces a loyalty program that boosts {PRODUCT} retention.", sentiment: 'positive', impactPercent: 0.19, sourceOffset: 9 },
  { text: "A government subsidy benefits {NAME}'s {PRODUCT} production.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 0 },
  { text: "{NAME} secures a long-term lease on a key {PRODUCT} manufacturing site.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 1 },
  { text: "A famous director features {NAME}'s {PRODUCT} in an upcoming film.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 2 },
  { text: "{NAME} reports that {PRODUCT} is now profitable on a unit basis.", sentiment: 'positive', impactPercent: 0.33, sourceOffset: 3 },
  { text: "A major logistics company partners with {NAME} to distribute {PRODUCT}.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 4 },
  { text: "{NAME} announces a stock split, making {TICKER} more accessible.", sentiment: 'positive', impactPercent: 0.21, sourceOffset: 5 },
  { text: "A leading university study validates the effectiveness of {NAME}'s {PRODUCT}.", sentiment: 'positive', impactPercent: 0.30, sourceOffset: 6 },
  { text: "{NAME} {GOOD_OUTCOME}, drawing praise from industry leaders.", sentiment: 'positive', impactPercent: 0.41, sourceOffset: 7 },
  { text: "A popular streaming show features {NAME}'s {PRODUCT} prominently.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, ahead of analyst expectations.", sentiment: 'positive', impactPercent: 0.36, sourceOffset: 9 },
  { text: "A major bank initiates coverage on {TICKER} with a 'Buy' rating.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} has reached 10 million users.", sentiment: 'positive', impactPercent: 0.32, sourceOffset: 1 },
  { text: "A prominent investor calls {TICKER} 'the most undervalued stock in the market.'", sentiment: 'positive', impactPercent: 0.39, sourceOffset: 2 },
  { text: "{NAME} announces a partnership with {RIVAL} to co-develop {PRODUCT}.", sentiment: 'positive', impactPercent: 0.34, sourceOffset: 3 },
  { text: "Trade data shows {NAME}'s {PRODUCT} exports surged this month.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 4 },
  { text: "{NAME} wins a prestigious design award for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 5 },
  { text: "A major conference invites {NAME}'s CEO to keynote about {PRODUCT}.", sentiment: 'positive', impactPercent: 0.18, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} customer churn dropped to an all-time low.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 7 },
  { text: "A famous musician mentions {NAME}'s {PRODUCT} in a hit song.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, expanding its total addressable market.", sentiment: 'positive', impactPercent: 0.38, sourceOffset: 9 },
  { text: "A leading think tank praises {NAME}'s approach to {PRODUCT}.", sentiment: 'positive', impactPercent: 0.20, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} now holds 30% market share.", sentiment: 'positive', impactPercent: 0.31, sourceOffset: 1 },
  { text: "A major airline agrees to use {NAME}'s {PRODUCT} in its operations.", sentiment: 'positive', impactPercent: 0.29, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, causing {RIVAL} to issue a defensive statement.", sentiment: 'positive', impactPercent: 0.40, sourceOffset: 3 },
  { text: "A popular review site gives {NAME}'s {PRODUCT} a perfect score.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 4 },
  { text: "{NAME} announces a new round of funding to scale {PRODUCT}.", sentiment: 'positive', impactPercent: 0.33, sourceOffset: 5 },
  { text: "A government report highlights {NAME}'s {PRODUCT} as an industry benchmark.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} subscription renewals hit a record high.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 7 },
  { text: "A famous chef endorses {NAME}'s {PRODUCT} in a cooking show.", sentiment: 'positive', impactPercent: 0.21, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, surprising the market positively.", sentiment: 'positive', impactPercent: 0.35, sourceOffset: 9 },
  { text: "A major insurer partners with {NAME} to offer warranties on {PRODUCT}.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} energy efficiency improved by 40%.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 1 },
  { text: "A leading environmental group certifies {NAME}'s {PRODUCT} as sustainable.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, boosting investor confidence in {TICKER}.", sentiment: 'positive', impactPercent: 0.39, sourceOffset: 3 },
  { text: "A major tech conference awards {NAME} 'Innovator of the Year' for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 4 },
  { text: "{NAME} announces a buy-one-give-one program for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.19, sourceOffset: 5 },
  { text: "A famous author features {NAME}'s {PRODUCT} in a bestselling novel.", sentiment: 'positive', impactPercent: 0.20, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} returned a record 90% gross margin.", sentiment: 'positive', impactPercent: 0.34, sourceOffset: 7 },
  { text: "A major hotel chain adopts {NAME}'s {PRODUCT} across all properties.", sentiment: 'positive', impactPercent: 0.29, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, entering a high-growth segment.", sentiment: 'positive', impactPercent: 0.37, sourceOffset: 9 },
  { text: "A leading labor union endorses {NAME}'s workplace practices for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.18, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} inventory turnover reached a record high.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 1 },
  { text: "A famous architect specifies {NAME}'s {PRODUCT} in a landmark project.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, winning praise from {RIVAL}'s former CEO.", sentiment: 'positive', impactPercent: 0.38, sourceOffset: 3 },
  { text: "A major sports league signs {NAME} as the official {PRODUCT} partner.", sentiment: 'positive', impactPercent: 0.31, sourceOffset: 4 },
  { text: "{NAME} announces a referral program that triples {PRODUCT} signups.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 5 },
  { text: "A leading safety institute awards {NAME}'s {PRODUCT} its top rating.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} average order value increased 25%.", sentiment: 'positive', impactPercent: 0.30, sourceOffset: 7 },
  { text: "A famous comedian jokes lovingly about {NAME}'s {PRODUCT} in a special.", sentiment: 'positive', impactPercent: 0.17, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, delighting long-term shareholders.", sentiment: 'positive', impactPercent: 0.36, sourceOffset: 9 },
  { text: "A major university adopts {NAME}'s {PRODUCT} for its research labs.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} net promoter score reached 80.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 1 },
  { text: "A leading fashion brand collaborates with {NAME} on a {PRODUCT} edition.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, causing analysts to revise {TICKER} estimates upward.", sentiment: 'positive', impactPercent: 0.43, sourceOffset: 3 },
  { text: "A major museum acquires {NAME}'s {PRODUCT} for its permanent collection.", sentiment: 'positive', impactPercent: 0.21, sourceOffset: 4 },
  { text: "{NAME} announces a sustainability report showing {PRODUCT} carbon neutrality.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 5 },
  { text: "A famous scientist cites {NAME}'s {PRODUCT} in a peer-reviewed paper.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} international sales grew 80%.", sentiment: 'positive', impactPercent: 0.33, sourceOffset: 7 },
  { text: "A major city names {NAME} its official {PRODUCT} provider.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, creating 5,000 new jobs.", sentiment: 'positive', impactPercent: 0.32, sourceOffset: 9 },
  { text: "A leading consumer group names {NAME}'s {PRODUCT} the best value of the year.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} warranty claims dropped to near zero.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 1 },
  { text: "A famous talk show host gifts {NAME}'s {PRODUCT} to the studio audience.", sentiment: 'positive', impactPercent: 0.29, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, prompting {RIVAL} to reconsider its strategy.", sentiment: 'positive', impactPercent: 0.40, sourceOffset: 3 },
  { text: "A major franchise features {NAME}'s {PRODUCT} in a blockbuster movie.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 4 },
  { text: "{NAME} announces a loyalty tier that locks in {PRODUCT} pricing.", sentiment: 'positive', impactPercent: 0.21, sourceOffset: 5 },
  { text: "A leading productivity blog names {NAME}'s {PRODUCT} an essential tool.", sentiment: 'positive', impactPercent: 0.20, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} repeat purchase rate hit 70%.", sentiment: 'positive', impactPercent: 0.31, sourceOffset: 7 },
  { text: "A major retailer names {NAME} its 'Vendor of the Year' for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, winning a government innovation grant.", sentiment: 'positive', impactPercent: 0.35, sourceOffset: 9 },
  { text: "A famous photographer shoots an ad campaign featuring {NAME}'s {PRODUCT}.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} app downloads surpassed 50 million.", sentiment: 'positive', impactPercent: 0.30, sourceOffset: 1 },
  { text: "A leading engineering society awards {NAME} a medal for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, leading to a credit rating upgrade for {TICKER}.", sentiment: 'positive', impactPercent: 0.37, sourceOffset: 3 },
  { text: "A major theme park installs {NAME}'s {PRODUCT} across the park.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 4 },
  { text: "{NAME} announces a trade-in program that boosts {PRODUCT} upgrades.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 5 },
  { text: "A famous novelist thanks {NAME}'s {PRODUCT} in an award speech.", sentiment: 'positive', impactPercent: 0.18, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} market share grew in every region.", sentiment: 'positive', impactPercent: 0.34, sourceOffset: 7 },
  { text: "A major cruise line equips its fleet with {NAME}'s {PRODUCT}.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, securing a celebrity ambassador.", sentiment: 'positive', impactPercent: 0.33, sourceOffset: 9 },
  { text: "A leading design school adds {NAME}'s {PRODUCT} to its curriculum.", sentiment: 'positive', impactPercent: 0.20, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} customer satisfaction is at a 5-year high.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 1 },
  { text: "A famous gamer streams {NAME}'s {PRODUCT} to 2 million viewers.", sentiment: 'positive', impactPercent: 0.29, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, attracting coverage from every major outlet.", sentiment: 'positive', impactPercent: 0.42, sourceOffset: 3 },
  { text: "A major stadium renames a section after {NAME}'s {PRODUCT}.", sentiment: 'positive', impactPercent: 0.21, sourceOffset: 4 },
  { text: "{NAME} announces a free trial that drives record {PRODUCT} signups.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 5 },
  { text: "A leading travel guide recommends {NAME}'s {PRODUCT} to tourists.", sentiment: 'positive', impactPercent: 0.19, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} gross profit doubled year-over-year.", sentiment: 'positive', impactPercent: 0.36, sourceOffset: 7 },
  { text: "A major publisher uses {NAME}'s {PRODUCT} in its editorial workflow.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, winning an industry innovation prize.", sentiment: 'positive', impactPercent: 0.34, sourceOffset: 9 },
  { text: "A famous historian praises {NAME}'s {PRODUCT} as 'a turning point.'", sentiment: 'positive', impactPercent: 0.20, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} on-time delivery reached 99%.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 1 },
  { text: "A leading medical journal cites {NAME}'s {PRODUCT} in a study.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, causing {TICKER} to hit a new all-time high.", sentiment: 'positive', impactPercent: 0.45, sourceOffset: 3 },
  { text: "A major festival names {NAME} its headline sponsor for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 4 },
  { text: "{NAME} announces a bundle that increases {PRODUCT} average revenue per user.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 5 },
  { text: "A famous podcaster dedicates an episode to {NAME}'s {PRODUCT}.", sentiment: 'positive', impactPercent: 0.21, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} referral rate hit 45%.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 7 },
  { text: "A major broadcaster uses {NAME}'s {PRODUCT} in its production pipeline.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, winning a sustainability award.", sentiment: 'positive', impactPercent: 0.33, sourceOffset: 9 },
  { text: "A leading think tank ranks {NAME} first in {PRODUCT} innovation.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} operating margin expanded to 35%.", sentiment: 'positive', impactPercent: 0.32, sourceOffset: 1 },
  { text: "A famous artist collaborates with {NAME} on a limited {PRODUCT} edition.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, leading to a front-page feature in a major paper.", sentiment: 'positive', impactPercent: 0.41, sourceOffset: 3 },
  { text: "A major transit authority adopts {NAME}'s {PRODUCT} system-wide.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 4 },
  { text: "{NAME} announces a financing round that values {TICKER} at a premium.", sentiment: 'positive', impactPercent: 0.30, sourceOffset: 5 },
  { text: "A leading startup accelerator selects {NAME} as a mentor for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.19, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} return rate fell to under 1%.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 7 },
  { text: "A major retailer reports {NAME}'s {PRODUCT} sold out in 3 minutes.", sentiment: 'positive', impactPercent: 0.35, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, securing a multi-year tax incentive.", sentiment: 'positive', impactPercent: 0.31, sourceOffset: 9 },
  { text: "A famous chef uses {NAME}'s {PRODUCT} in a Michelin-starred restaurant.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} wholesale orders grew 90%.", sentiment: 'positive', impactPercent: 0.33, sourceOffset: 1 },
  { text: "A leading architecture firm specifies {NAME}'s {PRODUCT} in all projects.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, prompting a rival to exit the market.", sentiment: 'positive', impactPercent: 0.44, sourceOffset: 3 },
  { text: "A major record label uses {NAME}'s {PRODUCT} in its studios.", sentiment: 'positive', impactPercent: 0.21, sourceOffset: 4 },
  { text: "{NAME} announces a warranty extension that boosts {PRODUCT} confidence.", sentiment: 'positive', impactPercent: 0.20, sourceOffset: 5 },
  { text: "A famous stylist features {NAME}'s {PRODUCT} in a magazine spread.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} enterprise contracts grew 50%.", sentiment: 'positive', impactPercent: 0.31, sourceOffset: 7 },
  { text: "A major university hospital adopts {NAME}'s {PRODUCT} clinically.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, winning a 'Best Place to Work' award.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 9 },
  { text: "A leading futurist predicts {NAME}'s {PRODUCT} will define the decade.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} free cash flow turned positive.", sentiment: 'positive', impactPercent: 0.34, sourceOffset: 1 },
  { text: "A famous director shoots a documentary about {NAME}'s {PRODUCT}.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, causing {RIVAL} to lose a key client.", sentiment: 'positive', impactPercent: 0.39, sourceOffset: 3 },
  { text: "A major league signs {NAME} as exclusive {PRODUCT} supplier.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 4 },
  { text: "{NAME} announces a price increase that the market accepts without protest.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 5 },
  { text: "A leading think tank invites {NAME} to advise on {PRODUCT} policy.", sentiment: 'positive', impactPercent: 0.20, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} active users grew 120% year-over-year.", sentiment: 'positive', impactPercent: 0.37, sourceOffset: 7 },
  { text: "A major retailer reports {NAME}'s {PRODUCT} is its top seller.", sentiment: 'positive', impactPercent: 0.30, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, winning a prestigious engineering prize.", sentiment: 'positive', impactPercent: 0.33, sourceOffset: 9 },
  { text: "A famous author dedicates a book to {NAME}'s {PRODUCT} team.", sentiment: 'positive', impactPercent: 0.18, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} customer lifetime value increased 40%.", sentiment: 'positive', impactPercent: 0.29, sourceOffset: 1 },
  { text: "A leading standards body adopts {NAME}'s {PRODUCT} spec as the industry norm.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, leading to a surge in institutional buying.", sentiment: 'positive', impactPercent: 0.42, sourceOffset: 3 },
  { text: "A major film studio uses {NAME}'s {PRODUCT} in its VFX pipeline.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 4 },
  { text: "{NAME} announces a referral partnership that expands {PRODUCT} reach.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 5 },
  { text: "A famous musician uses {NAME}'s {PRODUCT} on a world tour.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} gross merchandise volume hit a record.", sentiment: 'positive', impactPercent: 0.32, sourceOffset: 7 },
  { text: "A major city pilot program adopts {NAME}'s {PRODUCT} citywide.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, winning a global innovation award.", sentiment: 'positive', impactPercent: 0.34, sourceOffset: 9 },
  { text: "A leading venture capitalist calls {NAME} 'the next big thing in {PRODUCT}.'", sentiment: 'positive', impactPercent: 0.31, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} revenue per employee hit a record.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 1 },
  { text: "A famous architect uses {NAME}'s {PRODUCT} in an award-winning building.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, causing a wave of positive press coverage.", sentiment: 'positive', impactPercent: 0.40, sourceOffset: 3 },
  { text: "A major publisher features {NAME}'s {PRODUCT} in a textbook.", sentiment: 'positive', impactPercent: 0.20, sourceOffset: 4 },
  { text: "{NAME} announces a community grant program tied to {PRODUCT}.", sentiment: 'positive', impactPercent: 0.19, sourceOffset: 5 },
  { text: "A famous scientist joins {NAME}'s advisory board for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} sales pipeline grew 200%.", sentiment: 'positive', impactPercent: 0.35, sourceOffset: 7 },
  { text: "A major retailer extends {NAME}'s {PRODUCT} contract by 5 years.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, winning a customer excellence award.", sentiment: 'positive', impactPercent: 0.30, sourceOffset: 9 },
  { text: "A leading industry analyst calls {NAME}'s {PRODUCT} 'best-in-class.'", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} churn fell below 2%.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 1 },
  { text: "A famous talk show features {NAME}'s {PRODUCT} in a segment.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, leading to a feature in a major documentary.", sentiment: 'positive', impactPercent: 0.38, sourceOffset: 3 },
  { text: "A major sports team adopts {NAME}'s {PRODUCT} for training.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 4 },
  { text: "{NAME} announces a volume discount that drives {PRODUCT} bulk orders.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 5 },
  { text: "A leading magazine names {NAME} 'Brand of the Year' for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} international revenue surpassed domestic.", sentiment: 'positive', impactPercent: 0.33, sourceOffset: 7 },
  { text: "A major government agency selects {NAME}'s {PRODUCT} for a pilot.", sentiment: 'positive', impactPercent: 0.29, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, winning a diversity award.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 9 },
  { text: "A famous investor tweets that {TICKER} is 'going to the moon.'", sentiment: 'positive', impactPercent: 0.41, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} customer base grew 5x in 2 years.", sentiment: 'positive', impactPercent: 0.36, sourceOffset: 1 },
  { text: "A leading university endows a chair in {NAME}'s name for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, causing {RIVAL} to lose market share.", sentiment: 'positive', impactPercent: 0.43, sourceOffset: 3 },
  { text: "A major retailer reports {NAME}'s {PRODUCT} is its fastest seller.", sentiment: 'positive', impactPercent: 0.31, sourceOffset: 4 },
  { text: "{NAME} announces a sustainability bond to fund {PRODUCT} growth.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 5 },
  { text: "A famous comedian features {NAME}'s {PRODUCT} in a viral sketch.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} operating leverage improved significantly.", sentiment: 'positive', impactPercent: 0.30, sourceOffset: 7 },
  { text: "A major city awards {NAME} a contract to supply {PRODUCT}.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, winning a global quality award.", sentiment: 'positive', impactPercent: 0.32, sourceOffset: 9 },
  { text: "A leading think tank ranks {NAME} first in customer trust for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.26, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} revenue run rate hit $1 billion.", sentiment: 'positive', impactPercent: 0.38, sourceOffset: 1 },
  { text: "A famous designer collaborates with {NAME} on a {PRODUCT} capsule.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, leading to a surge in retail buying.", sentiment: 'positive', impactPercent: 0.41, sourceOffset: 3 },
  { text: "A major broadcaster features {NAME}'s {PRODUCT} in a primetime show.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 4 },
  { text: "{NAME} announces a partnership with a top logistics firm for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 5 },
  { text: "A famous athlete credits {NAME}'s {PRODUCT} for a record performance.", sentiment: 'positive', impactPercent: 0.27, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} subscription revenue grew 80%.", sentiment: 'positive', impactPercent: 0.34, sourceOffset: 7 },
  { text: "A major retailer reports {NAME}'s {PRODUCT} is its most returned-to item.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, winning a global design prize.", sentiment: 'positive', impactPercent: 0.31, sourceOffset: 9 },
  { text: "A leading analyst calls {NAME}'s {PRODUCT} 'the new industry standard.'", sentiment: 'positive', impactPercent: 0.29, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} gross margin hit a record 60%.", sentiment: 'positive', impactPercent: 0.33, sourceOffset: 1 },
  { text: "A famous musician features {NAME}'s {PRODUCT} in a music video.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, prompting a major bank to upgrade {TICKER}.", sentiment: 'positive', impactPercent: 0.40, sourceOffset: 3 },
  { text: "A major theme park features {NAME}'s {PRODUCT} in a new ride.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 4 },
  { text: "{NAME} announces a trade show that draws record {PRODUCT} interest.", sentiment: 'positive', impactPercent: 0.21, sourceOffset: 5 },
  { text: "A famous author features {NAME}'s {PRODUCT} in a bestseller.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} enterprise renewals hit 95%.", sentiment: 'positive', impactPercent: 0.28, sourceOffset: 7 },
  { text: "A major city names {NAME} its 'Partner of the Year' for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.24, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, winning a global safety award.", sentiment: 'positive', impactPercent: 0.30, sourceOffset: 9 },
  { text: "A leading consumer survey ranks {NAME}'s {PRODUCT} first in satisfaction.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 0 },
  { text: "{NAME} reports that {PRODUCT} average deal size grew 35%.", sentiment: 'positive', impactPercent: 0.29, sourceOffset: 1 },
  { text: "A famous chef features {NAME}'s {PRODUCT} in a cookbook.", sentiment: 'positive', impactPercent: 0.21, sourceOffset: 2 },
  { text: "{NAME} {GOOD_OUTCOME}, leading to a feature on a major news network.", sentiment: 'positive', impactPercent: 0.39, sourceOffset: 3 },
  { text: "A major sports league features {NAME}'s {PRODUCT} in a campaign.", sentiment: 'positive', impactPercent: 0.23, sourceOffset: 4 },
  { text: "{NAME} announces a customer advisory board for {PRODUCT}.", sentiment: 'positive', impactPercent: 0.19, sourceOffset: 5 },
  { text: "A famous director features {NAME}'s {PRODUCT} in a film scene.", sentiment: 'positive', impactPercent: 0.22, sourceOffset: 6 },
  { text: "{NAME} reports that {PRODUCT} win rate in deals improved to 70%.", sentiment: 'positive', impactPercent: 0.30, sourceOffset: 7 },
  { text: "A major retailer extends {NAME}'s {PRODUCT} exclusivity deal.", sentiment: 'positive', impactPercent: 0.25, sourceOffset: 8 },
  { text: "{NAME} announces it will {ACTION}, winning a global impact award.", sentiment: 'positive', impactPercent: 0.32, sourceOffset: 9 },

  // ==================== NEGATIVE (201-400) ====================
  { text: "Panic grips {TICKER} as {NAME} {BAD_OUTCOME}.", sentiment: 'negative', impactPercent: -0.33, sourceOffset: 0 },
  { text: "Short-seller report alleges {NAME} inflated {PRODUCT} sales figures.", sentiment: 'negative', impactPercent: -0.38, sourceOffset: 1 },
  { text: "Regulators open an investigation into {NAME}'s {PRODUCT} safety.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 2 },
  { text: "{NAME} misses earnings badly, citing weak {PRODUCT} demand.", sentiment: 'negative', impactPercent: -0.28, sourceOffset: 3 },
  { text: "Major customer cancels contract with {NAME} over {PRODUCT} defects.", sentiment: 'negative', impactPercent: -0.30, sourceOffset: 4 },
  { text: "{NAME} {BAD_OUTCOME}, forcing a recall of {PRODUCT}.", sentiment: 'negative', impactPercent: -0.35, sourceOffset: 5 },
  { text: "Class-action lawsuit filed against {NAME} regarding {PRODUCT}.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 6 },
  { text: "Key executive at {NAME} resigns abruptly amid {PRODUCT} concerns.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 7 },
  { text: "Rival {RIVAL} launches a superior {PRODUCT}, threatening {NAME}.", sentiment: 'negative', impactPercent: -0.27, sourceOffset: 8 },
  { text: "Analyst downgrades {TICKER} to 'Sell,' citing {PRODUCT} stagnation.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 9 },
  { text: "{NAME} announces it will {ACTION}, but the market reacts poorly.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 0 },
  { text: "Supply chain disruption hits {NAME}'s {PRODUCT} production.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 1 },
  { text: "Hedge fund dumps its entire {TICKER} position overnight.", sentiment: 'negative', impactPercent: -0.31, sourceOffset: 2 },
  { text: "{NAME} {BAD_OUTCOME}, causing a sharp drop in {TICKER}.", sentiment: 'negative', impactPercent: -0.34, sourceOffset: 3 },
  { text: "Consumer backlash grows over {NAME}'s {PRODUCT} pricing.", sentiment: 'negative', impactPercent: -0.18, sourceOffset: 4 },
  { text: "Leaked memo reveals {NAME} is struggling to ship {PRODUCT}.", sentiment: 'negative', impactPercent: -0.27, sourceOffset: 5 },
  { text: "Major retailer drops {NAME}'s {PRODUCT} from its shelves.", sentiment: 'negative', impactPercent: -0.29, sourceOffset: 6 },
  { text: "{NAME} reports a sharp decline in {PRODUCT} customer satisfaction.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 7 },
  { text: "Regulators fine {NAME} for misleading {PRODUCT} advertising.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 8 },
  { text: "A prominent investor shorts {TICKER}, citing {PRODUCT} concerns.", sentiment: 'negative', impactPercent: -0.30, sourceOffset: 9 },
  { text: "{NAME} {BAD_OUTCOME}, prompting a credit rating downgrade.", sentiment: 'negative', impactPercent: -0.32, sourceOffset: 0 },
  { text: "Trade dispute threatens {NAME}'s {PRODUCT} exports.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 1 },
  { text: "Cyberattack exposes {NAME}'s {PRODUCT} customer data.", sentiment: 'negative', impactPercent: -0.28, sourceOffset: 2 },
  { text: "{NAME} announces a hiring freeze, signaling {PRODUCT} trouble.", sentiment: 'negative', impactPercent: -0.19, sourceOffset: 3 },
  { text: "Major supplier cuts ties with {NAME} over {PRODUCT} disputes.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 4 },
  { text: "{NAME} reports a widening loss on {PRODUCT} development costs.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 5 },
  { text: "Influential blogger publishes a scathing review of {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 6 },
  { text: "{NAME} {BAD_OUTCOME}, leading to executive departures.", sentiment: 'negative', impactPercent: -0.33, sourceOffset: 7 },
  { text: "Options traders bet heavily against {TICKER} ahead of {PRODUCT} news.", sentiment: 'negative', impactPercent: -0.27, sourceOffset: 8 },
  { text: "Government subsidy for {NAME}'s {PRODUCT} is cut unexpectedly.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 9 },
  { text: "{NAME} loses a key patent lawsuit protecting {PRODUCT}.", sentiment: 'negative', impactPercent: -0.29, sourceOffset: 0 },
  { text: "Major customer switches to {RIVAL}, abandoning {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.28, sourceOffset: 1 },
  { text: "{NAME} announces it will {ACTION}, but faces regulatory pushback.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 2 },
  { text: "Industry survey shows {NAME}'s {PRODUCT} losing market share.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 3 },
  { text: "A famous celebrity ends their endorsement of {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 4 },
  { text: "{NAME} reports a spike in {PRODUCT} warranty claims.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 5 },
  { text: "Major bank cuts its {TICKER} price target by 40%.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 6 },
  { text: "{NAME} {BAD_OUTCOME}, drawing scrutiny from lawmakers.", sentiment: 'negative', impactPercent: -0.31, sourceOffset: 7 },
  { text: "A viral video mocks {NAME}'s {PRODUCT}, damaging its reputation.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 8 },
  { text: "{NAME} announces layoffs, citing weak {PRODUCT} demand.", sentiment: 'negative', impactPercent: -0.27, sourceOffset: 9 },
  { text: "Trade publication names {NAME}'s {PRODUCT} the worst in its class.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 0 },
  { text: "{NAME} reports a sharp drop in {PRODUCT} pre-orders.", sentiment: 'negative', impactPercent: -0.28, sourceOffset: 1 },
  { text: "A major retailer reports slow sales of {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 2 },
  { text: "{NAME} {BAD_OUTCOME}, causing a halt in {PRODUCT} shipments.", sentiment: 'negative', impactPercent: -0.34, sourceOffset: 3 },
  { text: "Regulators reject {NAME}'s application to expand {PRODUCT}.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 4 },
  { text: "A prominent analyst calls {TICKER} 'overvalued' on {PRODUCT} hype.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 5 },
  { text: "{NAME} reports a decline in {PRODUCT} gross margin.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 6 },
  { text: "Major logistics partner raises rates, hitting {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.19, sourceOffset: 7 },
  { text: "{NAME} announces it will {ACTION}, but faces a customer boycott.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 8 },
  { text: "A leading safety group flags {NAME}'s {PRODUCT} as hazardous.", sentiment: 'negative', impactPercent: -0.27, sourceOffset: 9 },
  { text: "{NAME} loses a major government contract for {PRODUCT}.", sentiment: 'negative', impactPercent: -0.29, sourceOffset: 0 },
  { text: "Industry data shows {NAME}'s {PRODUCT} returns surging.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 1 },
  { text: "{NAME} {BAD_OUTCOME}, prompting a sell-off in {TICKER}.", sentiment: 'negative', impactPercent: -0.35, sourceOffset: 2 },
  { text: "A famous investor publicly exits {TICKER}, citing {PRODUCT} doubts.", sentiment: 'negative', impactPercent: -0.30, sourceOffset: 3 },
  { text: "{NAME} reports a sharp increase in {PRODUCT} customer churn.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 4 },
  { text: "Major supplier raises prices, squeezing {NAME}'s {PRODUCT} margins.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 5 },
  { text: "{NAME} announces a delay in the {PRODUCT} launch timeline.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 6 },
  { text: "A leading consumer group downgrades {NAME}'s {PRODUCT} rating.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 7 },
  { text: "{NAME} reports a decline in {PRODUCT} international sales.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 8 },
  { text: "Major retailer reports excess inventory of {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 9 },
  { text: "{NAME} {BAD_OUTCOME}, causing {RIVAL} to gain market share.", sentiment: 'negative', impactPercent: -0.32, sourceOffset: 0 },
  { text: "Regulators impose new restrictions on {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 1 },
  { text: "A prominent short-seller targets {TICKER} in a detailed report.", sentiment: 'negative', impactPercent: -0.33, sourceOffset: 2 },
  { text: "{NAME} reports a decline in {PRODUCT} subscription renewals.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 3 },
  { text: "Major customer sues {NAME} over {PRODUCT} performance.", sentiment: 'negative', impactPercent: -0.27, sourceOffset: 4 },
  { text: "{NAME} announces it will {ACTION}, but faces union opposition.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 5 },
  { text: "A leading industry blog predicts {NAME}'s {PRODUCT} is a fad.", sentiment: 'negative', impactPercent: -0.19, sourceOffset: 6 },
  { text: "{NAME} reports a decline in {PRODUCT} app engagement.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 7 },
  { text: "Major retailer discounts {NAME}'s {PRODUCT} heavily to clear stock.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 8 },
  { text: "{NAME} {BAD_OUTCOME}, leading to a management shake-up.", sentiment: 'negative', impactPercent: -0.31, sourceOffset: 9 },
  { text: "Trade data shows {NAME}'s {PRODUCT} exports plummeted.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 0 },
  { text: "A famous reviewer calls {NAME}'s {PRODUCT} 'a disappointment.'", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 1 },
  { text: "{NAME} reports a decline in {PRODUCT} enterprise contracts.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 2 },
  { text: "Major partner ends collaboration with {NAME} on {PRODUCT}.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 3 },
  { text: "{NAME} announces it will {ACTION}, but faces legal challenges.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 4 },
  { text: "A leading think tank criticizes {NAME}'s {PRODUCT} strategy.", sentiment: 'negative', impactPercent: -0.19, sourceOffset: 5 },
  { text: "{NAME} reports a decline in {PRODUCT} average order value.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 6 },
  { text: "Major investor reduces stake in {TICKER} amid {PRODUCT} concerns.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 7 },
  { text: "{NAME} {BAD_OUTCOME}, prompting a regulatory audit.", sentiment: 'negative', impactPercent: -0.30, sourceOffset: 8 },
  { text: "A viral post criticizes {NAME}'s {PRODUCT}, sparking outrage.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 9 },
  { text: "{NAME} reports a decline in {PRODUCT} net promoter score.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 0 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is gathering dust.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 1 },
  { text: "{NAME} announces it will {ACTION}, but faces investor skepticism.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 2 },
  { text: "A leading analyst cuts {TICKER} estimates on {PRODUCT} weakness.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 3 },
  { text: "{NAME} reports a decline in {PRODUCT} wholesale orders.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 4 },
  { text: "Major customer complains publicly about {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 5 },
  { text: "{NAME} {BAD_OUTCOME}, causing a drop in employee morale.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 6 },
  { text: "A famous influencer retracts their endorsement of {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 7 },
  { text: "{NAME} reports a decline in {PRODUCT} free cash flow.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 8 },
  { text: "Major supplier delays shipments, hitting {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 9 },
  { text: "{NAME} announces it will {ACTION}, but faces cost overruns.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 0 },
  { text: "A leading industry report downgrades {NAME}'s {PRODUCT} outlook.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 1 },
  { text: "{NAME} reports a decline in {PRODUCT} customer retention.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 2 },
  { text: "Major retailer returns unsold {NAME} {PRODUCT} inventory.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 3 },
  { text: "{NAME} {BAD_OUTCOME}, leading to a credit watch.", sentiment: 'negative', impactPercent: -0.29, sourceOffset: 4 },
  { text: "A prominent blogger alleges {NAME} misled investors on {PRODUCT}.", sentiment: 'negative', impactPercent: -0.27, sourceOffset: 5 },
  { text: "{NAME} reports a decline in {PRODUCT} gross merchandise volume.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 6 },
  { text: "Major partner delays a joint {PRODUCT} launch with {NAME}.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 7 },
  { text: "{NAME} announces it will {ACTION}, but faces technical hurdles.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 8 },
  { text: "A leading consumer survey drops {NAME}'s {PRODUCT} ranking.", sentiment: 'negative', impactPercent: -0.19, sourceOffset: 9 },
  { text: "{NAME} reports a decline in {PRODUCT} revenue per user.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 0 },
  { text: "Major customer negotiates lower prices, hitting {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 1 },
  { text: "{NAME} {BAD_OUTCOME}, causing a drop in {TICKER} trading volume.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 2 },
  { text: "A famous analyst calls {NAME}'s {PRODUCT} 'a sinking ship.'", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 3 },
  { text: "{NAME} reports a decline in {PRODUCT} active users.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 4 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is being outsold by {RIVAL}.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 5 },
  { text: "{NAME} announces it will {ACTION}, but faces market resistance.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 6 },
  { text: "A leading industry group suspends {NAME}'s membership over {PRODUCT}.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 7 },
  { text: "{NAME} reports a decline in {PRODUCT} operating margin.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 8 },
  { text: "Major supplier files for bankruptcy, disrupting {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.27, sourceOffset: 9 },
  { text: "{NAME} {BAD_OUTCOME}, prompting a shareholder lawsuit.", sentiment: 'negative', impactPercent: -0.30, sourceOffset: 0 },
  { text: "A prominent investor activist demands changes at {NAME} over {PRODUCT}.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 1 },
  { text: "{NAME} reports a decline in {PRODUCT} international market share.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 2 },
  { text: "Major customer delays a {PRODUCT} order, hitting {NAME}'s revenue.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 3 },
  { text: "{NAME} announces it will {ACTION}, but faces environmental opposition.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 4 },
  { text: "A leading safety regulator opens a probe into {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 5 },
  { text: "{NAME} reports a decline in {PRODUCT} sales pipeline.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 6 },
  { text: "Major retailer cuts shelf space for {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 7 },
  { text: "{NAME} {BAD_OUTCOME}, causing a drop in {TICKER} after hours.", sentiment: 'negative', impactPercent: -0.28, sourceOffset: 8 },
  { text: "A famous journalist publishes an exposé on {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 9 },
  { text: "{NAME} reports a decline in {PRODUCT} customer lifetime value.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 0 },
  { text: "Major partner ends a co-marketing deal for {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 1 },
  { text: "{NAME} announces it will {ACTION}, but faces community pushback.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 2 },
  { text: "A leading industry analyst cuts {TICKER} to 'Underperform.'", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 3 },
  { text: "{NAME} reports a decline in {PRODUCT} subscription growth.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 4 },
  { text: "Major customer switches to a {RIVAL} alternative to {PRODUCT}.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 5 },
  { text: "{NAME} {BAD_OUTCOME}, leading to a drop in {TICKER} guidance.", sentiment: 'negative', impactPercent: -0.29, sourceOffset: 6 },
  { text: "A prominent short-seller alleges accounting fraud at {NAME}.", sentiment: 'negative', impactPercent: -0.32, sourceOffset: 7 },
  { text: "{NAME} reports a decline in {PRODUCT} deal win rate.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 8 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is being discounted.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 9 },
  { text: "{NAME} announces it will {ACTION}, but faces labor disputes.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 0 },
  { text: "A leading consumer group files a complaint about {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 1 },
  { text: "{NAME} reports a decline in {PRODUCT} enterprise renewals.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 2 },
  { text: "Major supplier raises material costs, hitting {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 3 },
  { text: "{NAME} {BAD_OUTCOME}, causing a drop in {TICKER} market cap.", sentiment: 'negative', impactPercent: -0.27, sourceOffset: 4 },
  { text: "A famous blogger alleges {NAME}'s {PRODUCT} is overhyped.", sentiment: 'negative', impactPercent: -0.19, sourceOffset: 5 },
  { text: "{NAME} reports a decline in {PRODUCT} referral rate.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 6 },
  { text: "Major customer reduces {PRODUCT} order volume from {NAME}.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 7 },
  { text: "{NAME} announces it will {ACTION}, but faces regulatory delays.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 8 },
  { text: "A leading industry report cuts {NAME}'s {PRODUCT} growth forecast.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 9 },
  { text: "{NAME} reports a decline in {PRODUCT} operating leverage.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 0 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is losing shelf appeal.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 1 },
  { text: "{NAME} {BAD_OUTCOME}, prompting a drop in {TICKER} price target.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 2 },
  { text: "A prominent analyst alleges {NAME}'s {PRODUCT} is obsolete.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 3 },
  { text: "{NAME} reports a decline in {PRODUCT} revenue run rate.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 4 },
  { text: "Major partner cancels a joint {PRODUCT} venture with {NAME}.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 5 },
  { text: "{NAME} announces it will {ACTION}, but faces supply shortages.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 6 },
  { text: "A leading consumer watchdog flags {NAME}'s {PRODUCT} pricing.", sentiment: 'negative', impactPercent: -0.19, sourceOffset: 7 },
  { text: "{NAME} reports a decline in {PRODUCT} gross profit.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 8 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is being returned en masse.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 9 },
  { text: "{NAME} {BAD_OUTCOME}, causing a drop in {TICKER} investor confidence.", sentiment: 'negative', impactPercent: -0.28, sourceOffset: 0 },
  { text: "A famous investor criticizes {NAME}'s {PRODUCT} strategy publicly.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 1 },
  { text: "{NAME} reports a decline in {PRODUCT} customer base.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 2 },
  { text: "Major customer delays payment, hitting {NAME}'s {PRODUCT} cash flow.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 3 },
  { text: "{NAME} announces it will {ACTION}, but faces quality issues.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 4 },
  { text: "A leading industry group downgrades {NAME}'s {PRODUCT} certification.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 5 },
  { text: "{NAME} reports a decline in {PRODUCT} sales velocity.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 6 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is being outsold by generics.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 7 },
  { text: "{NAME} {BAD_OUTCOME}, prompting a drop in {TICKER} ratings.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 8 },
  { text: "A prominent journalist alleges {NAME}'s {PRODUCT} is unsafe.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 9 },
  { text: "{NAME} reports a decline in {PRODUCT} market penetration.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 0 },
  { text: "Major partner ends a distribution deal for {NAME}'s {PRODUCT}.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 1 },
  { text: "{NAME} announces it will {ACTION}, but faces patent infringement claims.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 2 },
  { text: "A leading analyst cuts {TICKER} estimates on {PRODUCT} competition.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 3 },
  { text: "{NAME} reports a decline in {PRODUCT} customer loyalty.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 4 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is losing mindshare.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 5 },
  { text: "{NAME} {BAD_OUTCOME}, causing a drop in {TICKER} institutional holdings.", sentiment: 'negative', impactPercent: -0.27, sourceOffset: 6 },
  { text: "A famous blogger alleges {NAME}'s {PRODUCT} is a scam.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 7 },
  { text: "{NAME} reports a decline in {PRODUCT} brand awareness.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 8 },
  { text: "Major customer cancels a {PRODUCT} pilot with {NAME}.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 9 },
  { text: "{NAME} announces it will {ACTION}, but faces antitrust scrutiny.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 0 },
  { text: "A leading consumer group alleges {NAME}'s {PRODUCT} is misleading.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 1 },
  { text: "{NAME} reports a decline in {PRODUCT} repeat purchases.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 2 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is being clearanced.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 3 },
  { text: "{NAME} {BAD_OUTCOME}, prompting a drop in {TICKER} short interest.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 4 },
  { text: "A prominent short-seller alleges {NAME}'s {PRODUCT} is failing.", sentiment: 'negative', impactPercent: -0.28, sourceOffset: 5 },
  { text: "{NAME} reports a decline in {PRODUCT} customer engagement.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 6 },
  { text: "Major partner delays a {PRODUCT} integration with {NAME}.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 7 },
  { text: "{NAME} announces it will {ACTION}, but faces data privacy concerns.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 8 },
  { text: "A leading industry analyst cuts {TICKER} to 'Hold' on {PRODUCT} risks.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 9 },
  { text: "{NAME} reports a decline in {PRODUCT} average deal size.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 0 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is losing shelf space.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 1 },
  { text: "{NAME} {BAD_OUTCOME}, causing a drop in {TICKER} retail sentiment.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 2 },
  { text: "A famous reviewer calls {NAME}'s {PRODUCT} 'overpriced and underwhelming.'", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 3 },
  { text: "{NAME} reports a decline in {PRODUCT} conversion rate.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 4 },
  { text: "Major customer reduces {PRODUCT} contract size with {NAME}.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 5 },
  { text: "{NAME} announces it will {ACTION}, but faces funding concerns.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 6 },
  { text: "A leading safety group alleges {NAME}'s {PRODUCT} is defective.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 7 },
  { text: "{NAME} reports a decline in {PRODUCT} unit economics.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 8 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is being phased out.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 9 },
  { text: "{NAME} {BAD_OUTCOME}, prompting a drop in {TICKER} options volume.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 0 },
  { text: "A prominent investor alleges {NAME}'s {PRODUCT} is a bubble.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 1 },
  { text: "{NAME} reports a decline in {PRODUCT} customer acquisition.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 2 },
  { text: "Major partner ends a {PRODUCT} licensing deal with {NAME}.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 3 },
  { text: "{NAME} announces it will {ACTION}, but faces currency headwinds.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 4 },
  { text: "A leading industry report cuts {NAME}'s {PRODUCT} market share estimate.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 5 },
  { text: "{NAME} reports a decline in {PRODUCT} gross merchandise value.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 6 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is losing to {RIVAL}.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 7 },
  { text: "{NAME} {BAD_OUTCOME}, causing a drop in {TICKER} analyst sentiment.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 8 },
  { text: "A famous journalist alleges {NAME}'s {PRODUCT} is overpriced.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 9 },
  { text: "{NAME} reports a decline in {PRODUCT} customer satisfaction.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 0 },
  { text: "Major customer delays a {PRODUCT} rollout with {NAME}.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 1 },
  { text: "{NAME} announces it will {ACTION}, but faces leadership turmoil.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 2 },
  { text: "A leading consumer group alleges {NAME}'s {PRODUCT} is ineffective.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 3 },
  { text: "{NAME} reports a decline in {PRODUCT} sales productivity.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 4 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is being marked down.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 5 },
  { text: "{NAME} {BAD_OUTCOME}, prompting a drop in {TICKER} price.", sentiment: 'negative', impactPercent: -0.27, sourceOffset: 6 },
  { text: "A prominent short-seller alleges {NAME}'s {PRODUCT} is a fraud.", sentiment: 'negative', impactPercent: -0.30, sourceOffset: 7 },
  { text: "{NAME} reports a decline in {PRODUCT} customer trust.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 8 },
  { text: "Major partner ends a {PRODUCT} co-development deal with {NAME}.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 9 },
  { text: "{NAME} announces it will {ACTION}, but faces regulatory fines.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 0 },
  { text: "A leading industry analyst cuts {TICKER} to 'Reduce' on {PRODUCT} weakness.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 1 },
  { text: "{NAME} reports a decline in {PRODUCT} market position.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 2 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is being discontinued.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 3 },
  { text: "{NAME} {BAD_OUTCOME}, causing a drop in {TICKER} dividend outlook.", sentiment: 'negative', impactPercent: -0.25, sourceOffset: 4 },
  { text: "A famous blogger alleges {NAME}'s {PRODUCT} is failing quality tests.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 5 },
  { text: "{NAME} reports a decline in {PRODUCT} customer referrals.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 6 },
  { text: "Major customer cancels a {PRODUCT} expansion with {NAME}.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 7 },
  { text: "{NAME} announces it will {ACTION}, but faces competitive pressure.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 8 },
  { text: "A leading consumer group alleges {NAME}'s {PRODUCT} is unsafe for children.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 9 },
  { text: "{NAME} reports a decline in {PRODUCT} sales momentum.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 0 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is being replaced.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 1 },
  { text: "{NAME} {BAD_OUTCOME}, prompting a drop in {TICKER} guidance.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 2 },
  { text: "A prominent investor alleges {NAME}'s {PRODUCT} is overvalued.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 3 },
  { text: "{NAME} reports a decline in {PRODUCT} customer growth.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 4 },
  { text: "Major partner delays a {PRODUCT} launch with {NAME}.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 5 },
  { text: "{NAME} announces it will {ACTION}, but faces operational issues.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 6 },
  { text: "A leading industry report cuts {NAME}'s {PRODUCT} revenue forecast.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 7 },
  { text: "{NAME} reports a decline in {PRODUCT} gross margin.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 8 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is being liquidated.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 9 },
  { text: "{NAME} {BAD_OUTCOME}, causing a drop in {TICKER} earnings outlook.", sentiment: 'negative', impactPercent: -0.27, sourceOffset: 0 },
  { text: "A famous reviewer calls {NAME}'s {PRODUCT} 'a step backward.'", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 1 },
  { text: "{NAME} reports a decline in {PRODUCT} customer retention.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 2 },
  { text: "Major customer reduces {PRODUCT} commitment with {NAME}.", sentiment: 'negative', impactPercent: -0.20, sourceOffset: 3 },
  { text: "{NAME} announces it will {ACTION}, but faces legal action.", sentiment: 'negative', impactPercent: -0.23, sourceOffset: 4 },
  { text: "A leading safety group alleges {NAME}'s {PRODUCT} is hazardous.", sentiment: 'negative', impactPercent: -0.24, sourceOffset: 5 },
  { text: "{NAME} reports a decline in {PRODUCT} sales volume.", sentiment: 'negative', impactPercent: -0.22, sourceOffset: 6 },
  { text: "Major retailer reports {NAME}'s {PRODUCT} is being discounted heavily.", sentiment: 'negative', impactPercent: -0.21, sourceOffset: 7 },
  { text: "{NAME} {BAD_OUTCOME}, prompting a drop in {TICKER} price target.", sentiment: 'negative', impactPercent: -0.26, sourceOffset: 8 },
  { text: "A prominent short-seller alleges {NAME}'s {PRODUCT} is a house of cards.", sentiment: 'negative', impactPercent: -0.29, sourceOffset: 9 },

  // ==================== NEUTRAL (401-500) ====================
  { text: "Rumors circulate that {NAME} is considering a strategic shift for {PRODUCT}.", sentiment: 'neutral', impactPercent: 0.03, sourceOffset: 0 },
  { text: "Industry analysts debate whether {NAME}'s {PRODUCT} is ahead of its time.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 1 },
  { text: "{NAME} announces a minor rebranding of {PRODUCT}, with little market reaction.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 2 },
  { text: "Competitor {RIVAL} comments on {NAME}'s {PRODUCT}: 'We are monitoring.'", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 3 },
  { text: "{NAME} holds its annual meeting; CEO emphasizes {PRODUCT} stability.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 4 },
  { text: "Analysts are split on {NAME}'s decision to {ACTION}.", sentiment: 'neutral', impactPercent: -0.01, sourceOffset: 5 },
  { text: "A small study evaluates the environmental impact of {NAME}'s {PRODUCT}.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 6 },
  { text: "Leaked documents show {NAME} is exploring a {PRODUCT} variant.", sentiment: 'neutral', impactPercent: 0.04, sourceOffset: 7 },
  { text: "Global index rebalances; {TICKER} weight remains unchanged.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 8 },
  { text: "CEO of {NAME} seen dining with the founder of {RIVAL}.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 9 },
  { text: "{NAME} announces a pilot program for {PRODUCT} in a new market.", sentiment: 'neutral', impactPercent: 0.03, sourceOffset: 0 },
  { text: "Trade publication publishes a balanced profile of {NAME}'s {PRODUCT}.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 1 },
  { text: "{NAME} reports in-line earnings; {PRODUCT} performance met expectations.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 2 },
  { text: "Industry conference features a panel on {NAME}'s {PRODUCT} category.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 3 },
  { text: "{NAME} announces a minor {PRODUCT} update; analysts are neutral.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 4 },
  { text: "A leading magazine publishes a neutral review of {NAME}'s {PRODUCT}.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 5 },
  { text: "{NAME} announces a partnership exploration with {RIVAL} on {PRODUCT}.", sentiment: 'neutral', impactPercent: 0.03, sourceOffset: 6 },
  { text: "Analysts revise {TICKER} estimates slightly, citing {PRODUCT} trends.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 7 },
  { text: "{NAME} reports stable {PRODUCT} inventory levels.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 8 },
  { text: "Industry data shows {NAME}'s {PRODUCT} market share is flat.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 9 },
  { text: "{NAME} announces a leadership transition; {PRODUCT} strategy unchanged.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 0 },
  { text: "A leading blog publishes a speculative piece on {NAME}'s {PRODUCT} future.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 1 },
  { text: "{NAME} reports {PRODUCT} revenue in line with guidance.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 2 },
  { text: "Trade group releases a report mentioning {NAME}'s {PRODUCT} neutrally.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 3 },
  { text: "{NAME} announces a minor {PRODUCT} price adjustment.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 4 },
  { text: "Analysts maintain a 'Hold' on {TICKER}, citing {PRODUCT} uncertainty.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 5 },
  { text: "{NAME} reports {PRODUCT} customer satisfaction is stable.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 6 },
  { text: "Industry survey includes {NAME}'s {PRODUCT} without notable change.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 7 },
  { text: "{NAME} announces a {PRODUCT} beta test; results are pending.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 8 },
  { text: "A leading analyst publishes a neutral outlook on {TICKER}.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 9 },
  { text: "{NAME} reports {PRODUCT} gross margin is unchanged.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 0 },
  { text: "Industry conference mentions {NAME}'s {PRODUCT} in a broader panel.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 1 },
  { text: "{NAME} announces a {PRODUCT} survey; results are inconclusive.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 2 },
  { text: "Trade data shows {NAME}'s {PRODUCT} exports are flat.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 3 },
  { text: "{NAME} reports {PRODUCT} operating margin is stable.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 4 },
  { text: "Analysts revise {TICKER} price target slightly upward.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 5 },
  { text: "{NAME} announces a {PRODUCT} focus group; feedback is mixed.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 6 },
  { text: "Industry report lists {NAME}'s {PRODUCT} among several contenders.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 7 },
  { text: "{NAME} reports {PRODUCT} sales are in line with seasonal trends.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 8 },
  { text: "A leading magazine mentions {NAME}'s {PRODUCT} in a roundup.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 9 },
  { text: "{NAME} announces a {PRODUCT} roadmap; details are vague.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 0 },
  { text: "Analysts maintain a 'Neutral' on {TICKER}, awaiting {PRODUCT} news.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 1 },
  { text: "{NAME} reports {PRODUCT} customer churn is stable.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 2 },
  { text: "Industry data shows {NAME}'s {PRODUCT} adoption is gradual.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 3 },
  { text: "{NAME} announces a {PRODUCT} partnership exploration; terms undisclosed.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 4 },
  { text: "A leading blog publishes a balanced comparison of {NAME}'s {PRODUCT}.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 5 },
  { text: "{NAME} reports {PRODUCT} revenue is flat quarter-over-quarter.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 6 },
  { text: "Trade group mentions {NAME}'s {PRODUCT} in a regulatory filing.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 7 },
  { text: "{NAME} announces a {PRODUCT} pilot; results are expected next quarter.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 8 },
  { text: "Analysts revise {TICKER} estimates slightly downward.", sentiment: 'neutral', impactPercent: -0.01, sourceOffset: 9 },
  { text: "{NAME} reports {PRODUCT} gross profit is unchanged.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 0 },
  { text: "Industry conference features {NAME}'s {PRODUCT} in a neutral context.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 1 },
  { text: "{NAME} announces a {PRODUCT} survey; results are pending.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 2 },
  { text: "Trade data shows {NAME}'s {PRODUCT} imports are stable.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 3 },
  { text: "{NAME} reports {PRODUCT} operating expenses are in line.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 4 },
  { text: "Analysts maintain a 'Market Perform' on {TICKER}.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 5 },
  { text: "{NAME} announces a {PRODUCT} advisory board; impact is unclear.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 6 },
  { text: "Industry report includes {NAME}'s {PRODUCT} in a neutral analysis.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 7 },
  { text: "{NAME} reports {PRODUCT} sales are stable year-over-year.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 8 },
  { text: "A leading magazine publishes a neutral feature on {NAME}.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 9 },
  { text: "{NAME} announces a {PRODUCT} roadmap update; details are limited.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 0 },
  { text: "Analysts maintain a 'Sector Perform' on {TICKER}.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 1 },
  { text: "{NAME} reports {PRODUCT} customer base is stable.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 2 },
  { text: "Industry data shows {NAME}'s {PRODUCT} market is mature.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 3 },
  { text: "{NAME} announces a {PRODUCT} collaboration; terms are confidential.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 4 },
  { text: "A leading blog publishes a neutral overview of {NAME}'s {PRODUCT}.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 5 },
  { text: "{NAME} reports {PRODUCT} revenue is in line with consensus.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 6 },
  { text: "Trade group mentions {NAME}'s {PRODUCT} in a standards discussion.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 7 },
  { text: "{NAME} announces a {PRODUCT} study; results are awaited.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 8 },
  { text: "Analysts revise {TICKER} estimates; net impact is neutral.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 9 },
  { text: "{NAME} reports {PRODUCT} gross margin is stable.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 0 },
  { text: "Industry conference mentions {NAME}'s {PRODUCT} in passing.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 1 },
  { text: "{NAME} announces a {PRODUCT} review; outcome is uncertain.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 2 },
  { text: "Trade data shows {NAME}'s {PRODUCT} shipments are flat.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 3 },
  { text: "{NAME} reports {PRODUCT} operating income is unchanged.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 4 },
  { text: "Analysts maintain an 'Equal-weight' on {TICKER}.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 5 },
  { text: "{NAME} announces a {PRODUCT} task force; mandate is unclear.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 6 },
  { text: "Industry report lists {NAME}'s {PRODUCT} without comment.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 7 },
  { text: "{NAME} reports {PRODUCT} sales are consistent with trends.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 8 },
  { text: "A leading magazine mentions {NAME}'s {PRODUCT} in a listicle.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 9 },
  { text: "{NAME} announces a {PRODUCT} exploration; details are sparse.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 0 },
  { text: "Analysts maintain a 'Peer Perform' on {TICKER}.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 1 },
  { text: "{NAME} reports {PRODUCT} customer metrics are stable.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 2 },
  { text: "Industry data shows {NAME}'s {PRODUCT} category is saturated.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 3 },
  { text: "{NAME} announces a {PRODUCT} working group; impact is TBD.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 4 },
  { text: "A leading blog publishes a neutral update on {NAME}'s {PRODUCT}.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 5 },
  { text: "{NAME} reports {PRODUCT} revenue is flat year-over-year.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 6 },
  { text: "Trade group mentions {NAME}'s {PRODUCT} in a policy paper.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 7 },
  { text: "{NAME} announces a {PRODUCT} assessment; results are pending.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 8 },
  { text: "Analysts revise {TICKER} model; net impact is minimal.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 9 },
  { text: "{NAME} reports {PRODUCT} profitability is stable.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 0 },
  { text: "Industry conference includes {NAME}'s {PRODUCT} in a panel.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 1 },
  { text: "{NAME} announces a {PRODUCT} consultation; feedback is mixed.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 2 },
  { text: "Trade data shows {NAME}'s {PRODUCT} demand is steady.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 3 },
  { text: "{NAME} reports {PRODUCT} cash flow is in line.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 4 },
  { text: "Analysts maintain an 'In-line' rating on {TICKER}.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 5 },
  { text: "{NAME} announces a {PRODUCT} committee; scope is limited.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 6 },
  { text: "Industry report mentions {NAME}'s {PRODUCT} neutrally.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 7 },
  { text: "{NAME} reports {PRODUCT} metrics are consistent.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 8 },
  { text: "A leading magazine lists {NAME}'s {PRODUCT} without ranking.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 9 },
  { text: "{NAME} announces a {PRODUCT} initiative; details are forthcoming.", sentiment: 'neutral', impactPercent: 0.02, sourceOffset: 0 },
  { text: "Analysts maintain a 'Neutral' on {TICKER}, awaiting {PRODUCT} data.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 1 },
  { text: "{NAME} reports {PRODUCT} performance is in line with peers.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 2 },
  { text: "Industry data shows {NAME}'s {PRODUCT} segment is stable.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 3 },
  { text: "{NAME} announces a {PRODUCT} review; timeline is unclear.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 4 },
  { text: "A leading blog publishes a neutral summary of {NAME}'s {PRODUCT}.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 5 },
  { text: "{NAME} reports {PRODUCT} results are as expected.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 6 },
  { text: "Trade group mentions {NAME}'s {PRODUCT} in a newsletter.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 7 },
  { text: "{NAME} announces a {PRODUCT} evaluation; outcome is pending.", sentiment: 'neutral', impactPercent: 0.01, sourceOffset: 8 },
  { text: "Analysts revise {TICKER} outlook; net change is neutral.", sentiment: 'neutral', impactPercent: 0.00, sourceOffset: 9 }
];
