import { Company } from './types';

// 200 additional hand-crafted companies with specific, flavorful summaries.
// Each has a unique id, ticker, name, summary, category, basePrice, volatility, trend, and icon.
export const EXTRA_COMPANIES: Company[] = [
  // ---------- Tech (1-40) ----------
  {
    id: 'nxus',
    ticker: 'NXUS',
    name: 'Nexus Brainwave Labs',
    summary: 'Builds consumer-grade neural laces that let you check email by blinking. Early adopters report a 40% drop in typos and a 200% rise in existential dread.',
    category: 'Tech',
    basePrice: 175,
    volatility: 0.28,
    trend: 0.09,
    icon: '🧠'
  },
  {
    id: 'pixl',
    ticker: 'PIXL',
    name: 'Pixel Forge Studios',
    summary: 'Indie game studio that ships one pixel-perfect platformer every 18 months. Cult following, zero crunch, suspiciously profitable.',
    category: 'Tech',
    basePrice: 88,
    volatility: 0.22,
    trend: 0.07,
    icon: '🎮'
  },
  {
    id: 'qbit',
    ticker: 'QBIT',
    name: 'Qubit Horizon',
    summary: 'Quantum computing startup that promises to break all encryption "next quarter." Has been promising this for 9 years. Investors remain oddly optimistic.',
    category: 'Tech',
    basePrice: 210,
    volatility: 0.55,
    trend: 0.04,
    icon: '⚛️'
  },
  {
    id: 'holo',
    ticker: 'HOLO',
    name: 'HoloDeck Industries',
    summary: 'Manufactures consumer holographic projectors. Mostly used to project life-sized images of absent relatives at dinner parties. Surprisingly emotional product.',
    category: 'Tech',
    basePrice: 130,
    volatility: 0.30,
    trend: 0.08,
    icon: '👁️'
  },
  {
    id: 'synp',
    ticker: 'SYNP',
    name: 'Synapse Robotics',
    summary: 'Makes robotic prosthetics that are objectively better than the original limbs. Customers occasionally refuse the free "upgrade back to biological" program.',
    category: 'Tech',
    basePrice: 240,
    volatility: 0.20,
    trend: 0.11,
    icon: '🦾'
  },
  {
    id: 'claw',
    ticker: 'CLAW',
    name: 'Claw Machine AI',
    summary: 'Trained a neural network to win every claw machine on the planet. Now monetizes by selling winning coordinates to desperate parents at birthday parties.',
    category: 'Tech',
    basePrice: 42,
    volatility: 0.40,
    trend: 0.06,
    icon: '🕹️'
  },
  {
    id: 'drne',
    ticker: 'DRNE',
    name: 'Drone Symphony',
    summary: 'Choreographs swarms of delivery drones to perform orchestral music while dropping packages. Beautiful but frequently delivers parcels into koi ponds.',
    category: 'Tech',
    basePrice: 95,
    volatility: 0.35,
    trend: 0.05,
    icon: '🛸'
  },
  {
    id: 'glss',
    ticker: 'GLSS',
    name: 'Glasshouse Optics',
    summary: 'Produces smart glasses that overlay nutrition facts onto every food item you look at. Users report losing 12 pounds and all joy for dessert.',
    category: 'Tech',
    basePrice: 160,
    volatility: 0.25,
    trend: 0.07,
    icon: '👓'
  },
  {
    id: 'codx',
    ticker: 'CODX',
    name: 'Codex Autowriter',
    summary: 'AI that writes code by reading your mind through a webcam. Half its output is brilliant, the other half is the word "banana" repeated 4,000 times.',
    category: 'Tech',
    basePrice: 145,
    volatility: 0.45,
    trend: 0.10,
    icon: '💻'
  },
  {
    id: 'vrtx',
    ticker: 'VRTX',
    name: 'Vertex Cloud',
    summary: 'Runs the only cloud platform hosted entirely on servers buried in abandoned missile silos. Marketed as "the cloud that survives the apocalypse."',
    category: 'Tech',
    basePrice: 190,
    volatility: 0.18,
    trend: 0.06,
    icon: '☁️'
  },
  {
    id: 'lume',
    ticker: 'LUME',
    name: 'Lumina Display Co',
    summary: 'Invented a screen that is also a window. When turned off, it is just glass. Investors cannot decide if this is genius or nothing.',
    category: 'Tech',
    basePrice: 120,
    volatility: 0.32,
    trend: 0.05,
    icon: '🖼️'
  },
  {
    id: 'puls',
    ticker: 'PULS',
    name: 'Pulse Wearables',
    summary: 'Fitness band that shocks you gently when your posture is bad. Users stand perfectly straight at all times, including while sleeping.',
    category: 'Tech',
    basePrice: 65,
    volatility: 0.26,
    trend: 0.08,
    icon: '⌚'
  },
  {
    id: 'echo',
    ticker: 'ECHO',
    name: 'EchoSphere Audio',
    summary: 'Sells earbuds that translate every language in real-time, including baby cries and dog barks, into surprisingly passive-aggressive English.',
    category: 'Tech',
    basePrice: 110,
    volatility: 0.24,
    trend: 0.09,
    icon: '🎧'
  },
  {
    id: 'tide',
    ticker: 'TIDE',
    name: 'Tidal Compute',
    summary: 'Powers its data centers with ocean tides. Servers go offline for 6 hours a day during slack tide, which the company calls "intentional slow computing."',
    category: 'Tech',
    basePrice: 85,
    volatility: 0.30,
    trend: 0.04,
    icon: '🌊'
  },
  {
    id: 'noxa',
    ticker: 'NOXA',
    name: 'Noxaverse VR',
    summary: 'Virtual reality so immersive that 3% of users forget to log off and are found weeks later, thriving, in a digital suburb.',
    category: 'Tech',
    basePrice: 155,
    volatility: 0.42,
    trend: 0.07,
    icon: '🥽'
  },
  {
    id: 'zenn',
    ticker: 'ZENN',
    name: 'Zenith Notebook',
    summary: 'Sells a $400 paper notebook with a chip in the spine that does absolutely nothing. People buy it for the aesthetic. Profit margins are obscene.',
    category: 'Tech',
    basePrice: 70,
    volatility: 0.15,
    trend: 0.05,
    icon: '📓'
  },
  {
    id: 'flux',
    ticker: 'FLUX',
    name: 'Flux Capacitor Co',
    summary: 'Trademark dispute with a famous 80s movie, but they actually make flux capacitors for real. They just do not do anything interesting yet.',
    category: 'Tech',
    basePrice: 50,
    volatility: 0.50,
    trend: 0.02,
    icon: '🔌'
  },
  {
    id: 'mira',
    ticker: 'MIRA',
    name: 'Mirage Displays',
    summary: 'Makes holographic billboards visible only to people wearing their proprietary glasses. Pedestrians see nothing. Drivers are confused. Sales are up.',
    category: 'Tech',
    basePrice: 100,
    volatility: 0.33,
    trend: 0.06,
    icon: '📺'
  },
  {
    id: 'byte',
    ticker: 'BYTE',
    name: 'ByteForge Chips',
    summary: 'Fabricates processors so small they are technically theoretical. Engineers insist they work. Benchmark numbers are suspiciously round.',
    category: 'Tech',
    basePrice: 220,
    volatility: 0.38,
    trend: 0.08,
    icon: '🔩'
  },
  {
    id: 'wisp',
    ticker: 'WISP',
    name: 'Wisp Networks',
    summary: 'Provides internet via a fleet of high-altitude paper airplanes. Surprisingly reliable, except on windy days, which are most days.',
    category: 'Tech',
    basePrice: 60,
    volatility: 0.45,
    trend: 0.03,
    icon: '✈️'
  },
  {
    id: 'orbt',
    ticker: 'ORBT',
    name: 'Orbit OS',
    summary: 'An operating system that runs on satellites. Has 12 users, all of them satellites. Profitable because satellites pay well and never complain.',
    category: 'Tech',
    basePrice: 135,
    volatility: 0.20,
    trend: 0.07,
    icon: '🛰️'
  },
  {
    id: 'spkr',
    ticker: 'SPKR',
    name: 'Sonic Loom',
    summary: 'Weaves fabric that plays music when stretched. Popular for concert t-shirts. Unpopular for pajamas, due to involuntary 3 AM lullabies.',
    category: 'Tech',
    basePrice: 78,
    volatility: 0.28,
    trend: 0.06,
    icon: '🔊'
  },
  {
    id: 'ciph',
    ticker: 'CIPH',
    name: 'Cipher Vault',
    summary: 'Password manager that requires you to remember one master password, which it then forgets on your behalf for security reasons.',
    category: 'Tech',
    basePrice: 92,
    volatility: 0.22,
    trend: 0.05,
    icon: '🔐'
  },
  {
    id: 'glmr',
    ticker: 'GLMR',
    name: 'Glimmer Optics',
    summary: 'Camera lenses that make everything look like a 1970s home movie. Beloved by influencers who want to seem nostalgic for a decade they did not live in.',
    category: 'Tech',
    basePrice: 140,
    volatility: 0.26,
    trend: 0.06,
    icon: '📷'
  },
  {
    id: 'node',
    ticker: 'NODE',
    name: 'NodeMesh Systems',
    summary: 'Sells mesh Wi-Fi routers shaped like small woodland creatures. Coverage is excellent. Guests are unsettled by the staring felt eyes.',
    category: 'Tech',
    basePrice: 105,
    volatility: 0.19,
    trend: 0.07,
    icon: '🦔'
  },
  {
    id: 'przm',
    ticker: 'PRZM',
    name: 'Prism Analytics',
    summary: 'Dashboards so beautiful that executives stop making decisions and just stare at them. Revenue is up. Productivity is down. It balances out.',
    category: 'Tech',
    basePrice: 165,
    volatility: 0.21,
    trend: 0.08,
    icon: '📊'
  },
  {
    id: 'volt',
    ticker: 'VOLT',
    name: 'Voltaic Skin',
    summary: 'Solar-powered phone cases that charge your phone if you hold it directly toward the sun for 9 hours. Reviewers call it "technically accurate."',
    category: 'Tech',
    basePrice: 55,
    volatility: 0.34,
    trend: 0.04,
    icon: '🔋'
  },
  {
    id: 'haze',
    ticker: 'HAZE',
    name: 'Haze Filters',
    summary: 'Makes webcam filters that make you look awake, attentive, and fully clothed during meetings, regardless of the underlying reality.',
    category: 'Tech',
    basePrice: 48,
    volatility: 0.30,
    trend: 0.07,
    icon: '🌫️'
  },
  {
    id: 'crwn',
    ticker: 'CRWN',
    name: 'Crown Servers',
    summary: 'Sells servers plated in 24-karat gold. Performance is identical to normal servers. Buyers are exclusively rappers and one confused librarian.',
    category: 'Tech',
    basePrice: 280,
    volatility: 0.24,
    trend: 0.05,
    icon: '👑'
  },
  {
    id: 'drft',
    ticker: 'DRFT',
    name: 'Drift Keyboards',
    summary: 'Mechanical keyboards where each key is a tiny mechanical piano hammer. Typing an email sounds like a concerto. Coworkers hate it.',
    category: 'Tech',
    basePrice: 115,
    volatility: 0.27,
    trend: 0.06,
    icon: '🎹'
  },
  {
    id: 'lith',
    ticker: 'LITH',
    name: 'Lithic Storage',
    summary: 'Stores data by etching it into stone tablets with lasers. Read speed is terrible. Shelf life is 10,000 years. Archivists are thrilled.',
    category: 'Tech',
    basePrice: 90,
    volatility: 0.18,
    trend: 0.04,
    icon: '🪨'
  },
  {
    id: 'snyx',
    ticker: 'SNYX',
    name: 'Synthwave Audio',
    summary: 'Produces synthesizers that only play sounds from 1986. Has not updated its product line in 40 years. Sales grow 8% annually, mysteriously.',
    category: 'Tech',
    basePrice: 125,
    volatility: 0.20,
    trend: 0.06,
    icon: '🎚️'
  },
  {
    id: 'axnt',
    ticker: 'AXNT',
    name: 'Axion Displays',
    summary: 'Makes screens that are also mirrors. When off, you see yourself. When on, you see ads. Consumers report a strange sense of being judged.',
    category: 'Tech',
    basePrice: 150,
    volatility: 0.29,
    trend: 0.05,
    icon: '🪞'
  },
  {
    id: 'kryt',
    ticker: 'KRYT',
    name: 'Krypton Lenses',
    summary: 'AR contact lenses that overlay dad jokes onto every surface you look at. Returns are high. Retention among dads is even higher.',
    category: 'Tech',
    basePrice: 180,
    volatility: 0.36,
    trend: 0.07,
    icon: '👁️'
  },
  {
    id: 'tess',
    ticker: 'TESS',
    name: 'Tessera Tiles',
    summary: 'Smart floor tiles that charge devices placed on them. Also gently electrocute bare feet. The company calls this "a feature."',
    category: 'Tech',
    basePrice: 98,
    volatility: 0.31,
    trend: 0.05,
    icon: '🧩'
  },
  {
    id: 'halo',
    ticker: 'HALO',
    name: 'Halo Ring',
    summary: 'A smart ring that tracks your sleep, stress, and how many times you sigh per day. The sigh metric is, alarmingly, the most popular feature.',
    category: 'Tech',
    basePrice: 130,
    volatility: 0.23,
    trend: 0.08,
    icon: '💍'
  },
  {
    id: 'vexr',
    ticker: 'VEXR',
    name: 'Vexar Reality',
    summary: 'VR headsets that simulate a perfectly calm, slow, silent office. Marketed to people who work in open-plan hellscape startups.',
    category: 'Tech',
    basePrice: 200,
    volatility: 0.34,
    trend: 0.06,
    icon: '🌀'
  },
  {
    id: 'plsd',
    ticker: 'PLSD',
    name: 'Pulsed Networks',
    summary: 'Internet provider that only delivers data in 1-second pulses every 10 seconds. Cheaper than competitors. Gamers despise it. Emailers love it.',
    category: 'Tech',
    basePrice: 72,
    volatility: 0.25,
    trend: 0.04,
    icon: '📡'
  },
  {
    id: 'crst',
    ticker: 'CRST',
    name: 'Crystal Memory',
    summary: 'Stores data in 5D crystals. A single disc holds the entire internet. They have sold exactly 3 discs, all to governments who will not say why.',
    category: 'Tech',
    basePrice: 260,
    volatility: 0.40,
    trend: 0.05,
    icon: '💎'
  },
  {
    id: 'moss',
    ticker: 'MOSS',
    name: 'Mossfield Bio',
    summary: 'Grows living keyboards from genetically engineered moss. Keys regenerate if broken. Smells like a forest after rain. Slightly damp.',
    category: 'Tech',
    basePrice: 168,
    volatility: 0.33,
    trend: 0.09,
    icon: '🌿'
  },

  // ---------- Meme (41-70) ----------
  {
    id: 'pupr',
    ticker: 'PUPR',
    name: 'Purple Thing Inc',
    summary: 'Nobody knows what the company does. The product is just called "The Thing." It is purple. People buy it. The stock only goes up on Tuesdays.',
    category: 'Meme',
    basePrice: 30,
    volatility: 0.80,
    trend: 0.01,
    icon: '🟪'
  },
  {
    id: 'shoe',
    ticker: 'SHOE',
    name: 'One Shoe Co',
    summary: 'Sells only the left shoe. Right shoes are sold by a rival company. Customers must buy from both. The feud is entirely manufactured for marketing.',
    category: 'Meme',
    basePrice: 25,
    volatility: 0.70,
    trend: 0.03,
    icon: '👟'
  },
  {
    id: 'yak',
    ticker: 'YAK',
    name: 'Yak Shaving Ltd',
    summary: 'A company whose entire business model is the metaphor "yak shaving." They sell yak brushes. The yaks are not consulted. Stock spikes on Reddit mentions.',
    category: 'Meme',
    basePrice: 18,
    volatility: 0.85,
    trend: -0.01,
    icon: '🐃'
  },
  {
    id: 'tofu',
    ticker: 'TOFU',
    name: 'Tofu Empire',
    summary: 'A meme stock that started as a joke about tofu. Now controls 40% of the global soy market. The original joke account has been silent for 3 years.',
    category: 'Meme',
    basePrice: 55,
    volatility: 0.60,
    trend: 0.05,
    icon: '🧈'
  },
  {
    id: 'llma',
    ticker: 'LLMA',
    name: 'Llama Drama Corp',
    summary: 'Breeders of extremely dramatic llamas. Each llama has its own social media account. The llamas have more followers than the CEO.',
    category: 'Meme',
    basePrice: 22,
    volatility: 0.75,
    trend: 0.02,
    icon: '🦙'
  },
  {
    id: 'pnck',
    ticker: 'PNCK',
    name: 'Pancake Cartel',
    summary: 'A meme-driven pancake delivery service. They only deliver on Sundays. They only accept tips in the form of compliments. Surprisingly solvent.',
    category: 'Meme',
    basePrice: 28,
    volatility: 0.65,
    trend: 0.04,
    icon: '🥞'
  },
  {
    id: 'frog',
    ticker: 'FROG',
    name: 'Sad Frog Holdings',
    summary: 'Owns the rights to a single image of a melancholy frog. Licensing revenue is somehow enough to fund a 200-person office in downtown Manhattan.',
    category: 'Meme',
    basePrice: 40,
    volatility: 0.78,
    trend: 0.01,
    icon: '🐸'
  },
  {
    id: 'brrr',
    ticker: 'BRRR',
    name: 'Money Printer Go',
    summary: 'A company that literally just prints novelty money with memes on it. Technically legal. Morally confusing. Hugely popular at office parties.',
    category: 'Meme',
    basePrice: 15,
    volatility: 0.88,
    trend: -0.02,
    icon: '🖨️'
  },
  {
    id: 'clwn',
    ticker: 'CLWN',
    name: 'Clown World Co',
    summary: 'Sells clown noses to corporate executives as a "team building exercise." 90% of buyers keep the nose on their desk, untouched, forever.',
    category: 'Meme',
    basePrice: 12,
    volatility: 0.82,
    trend: 0.00,
    icon: '🤡'
  },
  {
    id: 'vibe',
    ticker: 'VIBE',
    name: 'Vibe Check Inc',
    summary: 'A service that, for $5, sends a stranger to your location to assess your vibe. The assessment is always "mid." Customers keep rebooking.',
    category: 'Meme',
    basePrice: 35,
    volatility: 0.72,
    trend: 0.03,
    icon: '😎'
  },
  {
    id: 'gnch',
    ticker: 'GNCH',
    name: 'Gnome Home Guard',
    summary: 'Manufactures garden gnomes that are also security cameras. Thieves report feeling deeply judged, not watched, when stealing from these gardens.',
    category: 'Meme',
    basePrice: 48,
    volatility: 0.55,
    trend: 0.06,
    icon: '🧙'
  },
  {
    id: 'shrk',
    ticker: 'SHRK',
    name: 'Shark With Legs',
    summary: 'A genetic engineering meme company trying to give sharks legs. Has not succeeded. Has burned $400 million. Stock is up 300% this year.',
    category: 'Meme',
    basePrice: 60,
    volatility: 0.90,
    trend: 0.04,
    icon: '🦈'
  },
  {
    id: 'tues',
    ticker: 'TUES',
    name: 'Taco Tuesday LLC',
    summary: 'Owns the trademark on the concept of Tuesday. Sues restaurants that serve tacos on other days. Universally despised. Wildly profitable.',
    category: 'Meme',
    basePrice: 75,
    volatility: 0.50,
    trend: 0.07,
    icon: '🌮'
  },
  {
    id: 'bnny',
    ticker: 'BNNY',
    name: 'Bunny Hop Industries',
    summary: 'Teaches rabbits to do agility courses. The rabbits are unimpressed. The internet is obsessed. Merch sales fund the entire operation.',
    category: 'Meme',
    basePrice: 20,
    volatility: 0.68,
    trend: 0.02,
    icon: '🐰'
  },
  {
    id: 'pot8',
    ticker: 'POT8',
    name: 'Potato Eight',
    summary: 'A company that sells exactly eight potatoes, no more, no less, for $80. The potatoes are normal. The branding is immaculate. The customers are devoted.',
    category: 'Meme',
    basePrice: 80,
    volatility: 0.60,
    trend: 0.05,
    icon: '🥔'
  },
  {
    id: 'wink',
    ticker: 'WINK',
    name: 'Wink Emoji Co',
    summary: 'Holds the licensing rights to the winking emoji. Every time someone uses it in a corporate email, they get 0.001 cents. Volume is staggering.',
    category: 'Meme',
    basePrice: 95,
    volatility: 0.45,
    trend: 0.08,
    icon: '😉'
  },
  {
    id: 'drty',
    ticker: 'DRTY',
    name: 'Dirty Sock Exchange',
    summary: 'A marketplace for trading worn socks. The company insists it is for "athletic research." Analysts do not ask follow-up questions.',
    category: 'Meme',
    basePrice: 10,
    volatility: 0.95,
    trend: -0.03,
    icon: '🧦'
  },
  {
    id: 'mlem',
    ticker: 'MLEM',
    name: 'Mlem Industries',
    summary: 'Sells recordings of cats making the "mlem" sound, as 10-hour ambient loops. Streamed in 14 million offices as "focus audio."',
    category: 'Meme',
    basePrice: 32,
    volatility: 0.66,
    trend: 0.04,
    icon: '😺'
  },
  {
    id: 'boop',
    ticker: 'BOOP',
    name: 'Boop The Snoot',
    summary: 'A subscription service that delivers a single boop to your dog\'s snoot each morning, by a trained professional. Dogs are confused. Owners are delighted.',
    category: 'Meme',
    basePrice: 27,
    volatility: 0.74,
    trend: 0.02,
    icon: '🐶'
  },
  {
    id: 'yeet',
    ticker: 'YEET',
    name: 'Yeet Logistics',
    summary: 'A delivery company whose entire strategy is throwing packages from moving vans toward your door. 60% success rate. Customers find it hilarious.',
    category: 'Meme',
    basePrice: 14,
    volatility: 0.92,
    trend: -0.01,
    icon: '📦'
  },
  {
    id: 'oof',
    ticker: 'OOF',
    name: 'Big Oof Energy',
    summary: 'Sells cans of "oof energy drink" that taste like regret and carbonation. Sales spike every Monday. The company has never run an ad.',
    category: 'Meme',
    basePrice: 19,
    volatility: 0.80,
    trend: 0.01,
    icon: '🥤'
  },
  {
    id: 'sus',
    ticker: 'SUS',
    name: 'Sus Amogus Corp',
    summary: 'Makes bean-shaped plushies of ambiguous identity. The plushies are always "acting suspicious." Children love them. Parents are mildly concerned.',
    category: 'Meme',
    basePrice: 23,
    volatility: 0.77,
    trend: 0.03,
    icon: '🫘'
  },
  {
    id: 'bruh',
    ticker: 'BRUH',
    name: 'Bruh Moment Ltd',
    summary: 'A holding company whose only asset is a single viral video of a man saying "bruh." It has been licensed 4 million times. The man is now a millionaire.',
    category: 'Meme',
    basePrice: 45,
    volatility: 0.58,
    trend: 0.05,
    icon: '🤷'
  },
  {
    id: 'noir',
    ticker: 'NOIR',
    name: 'Noir Cat Pictures',
    summary: 'Produces black-and-white films starring exclusively cats. The cats are paid in tuna. The films are shown at Cannes. Critics are baffled.',
    category: 'Meme',
    basePrice: 38,
    volatility: 0.52,
    trend: 0.04,
    icon: '🐈‍⬛'
  },
  {
    id: 'wigl',
    ticker: 'WIGL',
    name: 'Wiggle Worm Co',
    summary: 'Sells jars of worms that wiggle on command. The command is "wiggle." It always works. Biology professors refuse to explain why.',
    category: 'Meme',
    basePrice: 16,
    volatility: 0.83,
    trend: 0.00,
    icon: '🪱'
  },
  {
    id: 'honk',
    ticker: 'HONK',
    name: 'Honk Goose Brigade',
    summary: 'A service that releases 12 geese into your enemy\'s yard. The geese honk for 6 hours, then leave. Legal in 40 states. Banned in the other 10.',
    category: 'Meme',
    basePrice: 50,
    volatility: 0.70,
    trend: 0.02,
    icon: '🦢'
  },
  {
    id: 'smol',
    ticker: 'SMOL',
    name: 'Smol Bean Holdings',
    summary: 'Invests exclusively in companies that make small versions of large things. Tiny fridges, miniature horses, baby elephants. Returns are consistent.',
    category: 'Meme',
    basePrice: 42,
    volatility: 0.48,
    trend: 0.06,
    icon: '🫘'
  },
  {
    id: 'chon',
    ticker: 'CHON',
    name: 'Chonky Cat Fund',
    summary: 'A hedge fund that only invests in cat food companies. Run by a cat named Chairman Meow. The cat has a better 5-year return than most humans.',
    category: 'Meme',
    basePrice: 65,
    volatility: 0.50,
    trend: 0.07,
    icon: '🐈'
  },
  {
    id: 'derp',
    ticker: 'DERP',
    name: 'Derp Face Studios',
    summary: 'Sells NFTs of intentionally bad portraits. The worse the art, the higher the price. The "worst" piece sold for $1.2 million.',
    category: 'Meme',
    basePrice: 33,
    volatility: 0.86,
    trend: -0.02,
    icon: '🤪'
  },
  {
    id: 'noot',
    ticker: 'NOOT',
    name: 'Noot Noot Inc',
    summary: 'Owns the rights to a penguin saying "noot noot." Every penguin documentary pays royalties. The penguin has been dead for 12 years.',
    category: 'Meme',
    basePrice: 28,
    volatility: 0.69,
    trend: 0.03,
    icon: '🐧'
  },

  // ---------- Crypto (71-110) ----------
  {
    id: 'ethx',
    ticker: 'ETHX',
    name: 'Ethermax Plus',
    summary: 'A blockchain that processes 0.3 transactions per second but charges $40 in fees per transaction. Users defend it passionately in 10,000-word forum posts.',
    category: 'Crypto',
    basePrice: 320,
    volatility: 0.80,
    trend: 0.08,
    icon: '⟠'
  },
  {
    id: 'shib',
    ticker: 'SHIB',
    name: 'Shiba Inu Moon',
    summary: 'A token named after a dog that is named after a token that is named after a dog. No one remembers which came first. Market cap: $4 billion.',
    category: 'Crypto',
    basePrice: 8,
    volatility: 0.95,
    trend: 0.02,
    icon: '🐕'
  },
  {
    id: 'luna',
    ticker: 'LUNA',
    name: 'Luna Classic 2',
    summary: 'A "stablecoin" pegged to the value of one moon rock. The moon rock has been missing since 2019. The peg has held, somehow.',
    category: 'Crypto',
    basePrice: 1,
    volatility: 0.30,
    trend: 0.00,
    icon: '🌙'
  },
  {
    id: 'sol',
    ticker: 'SOL',
    name: 'Solana Killer',
    summary: 'A blockchain so fast it processes transactions before they are submitted. Users report buying things they have not yet decided to buy.',
    category: 'Crypto',
    basePrice: 180,
    volatility: 0.75,
    trend: 0.10,
    icon: '◎'
  },
  {
    id: 'ada',
    ticker: 'ADA',
    name: 'Cardano Max',
    summary: 'A blockchain that has been "about to ship smart contracts" for 7 years. The community refers to this as "peer-reviewed timelines."',
    category: 'Crypto',
    basePrice: 95,
    volatility: 0.70,
    trend: 0.03,
    icon: '₳'
  },
  {
    id: 'dot',
    ticker: 'DOT',
    name: 'Polka Dot Chain',
    summary: 'A network of parachains that all look identical but insist they are different. The founders wear polka-dot shirts to every conference. It is their whole identity.',
    category: 'Crypto',
    basePrice: 110,
    volatility: 0.72,
    trend: 0.04,
    icon: '●'
  },
  {
    id: 'matic',
    ticker: 'MATIC',
    name: 'Polygon Pro',
    summary: 'A layer-2 scaling solution that makes transactions cheaper by putting them on a different blockchain and pretending they are the same one.',
    category: 'Crypto',
    basePrice: 75,
    volatility: 0.68,
    trend: 0.06,
    icon: '🟣'
  },
  {
    id: 'avax',
    ticker: 'AVAX',
    name: 'Avalanche Rush',
    summary: 'A blockchain marketed as "blazing fast." It is, in fact, fast. It is also frequently down. The team calls outages "scheduled cooling periods."',
    category: 'Crypto',
    basePrice: 140,
    volatility: 0.78,
    trend: 0.05,
    icon: '🔺'
  },
  {
    id: 'link',
    ticker: 'LINK',
    name: 'Chainlink Oracle',
    summary: 'Connects smart contracts to real-world data. Mostly used to settle bets about whether it will rain. Settles $2 billion in weather bets daily.',
    category: 'Crypto',
    basePrice: 60,
    volatility: 0.65,
    trend: 0.07,
    icon: '🔗'
  },
  {
    id: 'uni',
    ticker: 'UNI',
    name: 'Unicorn Swap',
    summary: 'A decentralized exchange with a unicorn logo. Liquidity providers earn fees in a token that is worth less every month. They keep providing liquidity.',
    category: 'Crypto',
    basePrice: 85,
    volatility: 0.74,
    trend: 0.02,
    icon: '🦄'
  },
  {
    id: 'aave',
    ticker: 'AAVE',
    name: 'Ghost Lending',
    summary: 'A lending protocol named after the Finnish word for "ghost." Your deposits vanish mysteriously. The team insists this is "by design."',
    category: 'Crypto',
    basePrice: 200,
    volatility: 0.76,
    trend: 0.04,
    icon: '👻'
  },
  {
    id: 'comp',
    ticker: 'COMP',
    name: 'Compound Interest',
    summary: 'A protocol where you lend money to strangers on the internet and earn 0.2% APY. The strangers sometimes do not give the money back. This is called "innovation."',
    category: 'Crypto',
    basePrice: 130,
    volatility: 0.70,
    trend: 0.03,
    icon: '📈'
  },
  {
    id: 'snx',
    ticker: 'SNX',
    name: 'Synthetix Assets',
    summary: 'Mints synthetic versions of real assets. You can buy synthetic gold, synthetic oil, and synthetic Tesla stock. None of it is real. All of it trades.',
    category: 'Crypto',
    basePrice: 90,
    volatility: 0.82,
    trend: 0.05,
    icon: '🎭'
  },
  {
    id: 'crv',
    ticker: 'CRV',
    name: 'Curve Stable',
    summary: 'An exchange that only trades between stablecoins that are all worth $1. It somehow generates $500 million in fees. Mathematicians are concerned.',
    category: 'Crypto',
    basePrice: 45,
    volatility: 0.66,
    trend: 0.02,
    icon: '🌊'
  },
  {
    id: 'bal',
    ticker: 'BAL',
    name: 'Balancer Pool',
    summary: 'A protocol that automatically rebalances your portfolio. It rebalances so often that you end up with less money than you started with, but the chart looks great.',
    category: 'Crypto',
    basePrice: 55,
    volatility: 0.69,
    trend: 0.01,
    icon: '⚖️'
  },
  {
    id: 'yfi',
    ticker: 'YFI',
    name: 'Yearn Finance',
    summary: 'A token that was distributed for free and then became worth $40,000 each. The founder was surprised. Everyone else was furious they did not claim any.',
    category: 'Crypto',
    basePrice: 8000,
    volatility: 0.85,
    trend: 0.06,
    icon: '🤑'
  },
  {
    id: 'sushi',
    ticker: 'SUSHI',
    name: 'Sushi Swap',
    summary: 'A fork of another exchange, started by a chef who later sold all his tokens and disappeared. The protocol still runs. The chef is on a boat somewhere.',
    category: 'Crypto',
    basePrice: 35,
    volatility: 0.80,
    trend: 0.02,
    icon: '🍣'
  },
  {
    id: 'cake',
    ticker: 'CAKE',
    name: 'Pancake Swap',
    summary: 'A decentralized exchange themed entirely around pancakes. The token is called CAKE. The pools are called syrup. The users are called hungry.',
    category: 'Crypto',
    basePrice: 25,
    volatility: 0.83,
    trend: 0.03,
    icon: '🥞'
  },
  {
    id: 'doge2',
    ticker: 'DOGC',
    name: 'Doge Classic',
    summary: 'The original meme coin. Created as a joke in 2013. Now used to tip people on the internet for being funny. Has a market cap larger than some countries.',
    category: 'Crypto',
    basePrice: 15,
    volatility: 0.90,
    trend: 0.04,
    icon: '🐕'
  },
  {
    id: 'pepe',
    ticker: 'PEPE',
    name: 'Pepe Cash',
    summary: 'A token based on a frog meme from 2005. The creator did not make any money from it. Everyone else did. The creator is mildly annoyed.',
    category: 'Crypto',
    basePrice: 5,
    volatility: 0.98,
    trend: 0.01,
    icon: '🐸'
  },
  {
    id: 'floki',
    ticker: 'FLOKI',
    name: 'Floki Inu',
    summary: 'Named after a Viking and a dog. The marketing budget is larger than the development budget. Billboards in 40 cities. Code has not been updated in 2 years.',
    category: 'Crypto',
    basePrice: 3,
    volatility: 0.96,
    trend: 0.00,
    icon: '🐺'
  },
  {
    id: 'shib2',
    ticker: 'SHBR',
    name: 'Shibarium Layer',
    summary: 'A layer-2 for a meme coin that nobody asked for. It launched, broke immediately, was relaunched, and now processes 11 transactions per day.',
    category: 'Crypto',
    basePrice: 2,
    volatility: 0.94,
    trend: -0.01,
    icon: '🐕'
  },
  {
    id: 'bone',
    ticker: 'BONE',
    name: 'Bone Governance',
    summary: 'The governance token for a meme coin ecosystem. Holders vote on proposals like "should we make another token." The answer is always yes.',
    category: 'Crypto',
    basePrice: 12,
    volatility: 0.88,
    trend: 0.02,
    icon: '🦴'
  },
  {
    id: 'leash',
    ticker: 'LEASH',
    name: 'Doge Leash',
    summary: 'A token with a supply of exactly 100,000. Each one is worth a lot. Nobody knows what it does. Holders refer to themselves as "the leashed."',
    category: 'Crypto',
    basePrice: 450,
    volatility: 0.87,
    trend: 0.03,
    icon: '🦮'
  },
  {
    id: 'safe',
    ticker: 'SAFE',
    name: 'SafeMoon Protocol',
    summary: 'A token that charges a 10% tax on every sale, half of which is distributed to existing holders. This is called "safety." Regulators disagree.',
    category: 'Crypto',
    basePrice: 1,
    volatility: 0.99,
    trend: -0.05,
    icon: '🌙'
  },
  {
    id: 'btcp',
    ticker: 'BTCP',
    name: 'Bitcoin Platinum',
    summary: 'A "better Bitcoin" that is actually just Bitcoin with a different name and 90% less security. The team insists it is the future.',
    category: 'Crypto',
    basePrice: 250,
    volatility: 0.82,
    trend: 0.02,
    icon: '🥇'
  },
  {
    id: 'usdc',
    ticker: 'USDC',
    name: 'USD Coin Pro',
    summary: 'A stablecoin that is supposedly backed 1:1 by dollars. The reserves are held in a vault that no one has ever seen. Audits are "coming soon."',
    category: 'Crypto',
    basePrice: 1,
    volatility: 0.05,
    trend: 0.00,
    icon: '💵'
  },
  {
    id: 'dai',
    ticker: 'DAI',
    name: 'Dai Stable',
    summary: 'A stablecoin backed by other crypto tokens that are themselves volatile. It has maintained its $1 peg through sheer force of community belief.',
    category: 'Crypto',
    basePrice: 1,
    volatility: 0.08,
    trend: 0.00,
    icon: '🟡'
  },
  {
    id: 'frax',
    ticker: 'FRAX',
    name: 'Frax Fractional',
    summary: 'A "fractionally algorithmic" stablecoin, which is a fancy way of saying "sometimes it is backed by dollars and sometimes by vibes."',
    category: 'Crypto',
    basePrice: 1,
    volatility: 0.12,
    trend: 0.00,
    icon: '🧮'
  },
  {
    id: 'tusd',
    ticker: 'TUSD',
    name: 'True Dollar',
    summary: 'A stablecoin that claims to be "more true" than other dollars. The distinction is philosophical. The price is the same. The fees are higher.',
    category: 'Crypto',
    basePrice: 1,
    volatility: 0.06,
    trend: 0.00,
    icon: '💯'
  },
  {
    id: 'ens',
    ticker: 'ENS',
    name: 'Ethereum Names',
    summary: 'Sells human-readable names for crypto addresses, like "myname.eth." The most desirable names sell for millions. "weather.eth" sold for $80,000.',
    category: 'Crypto',
    basePrice: 40,
    volatility: 0.73,
    trend: 0.05,
    icon: '🏷️'
  },
  {
    id: 'gala',
    ticker: 'GALA',
    name: 'Gala Games',
    summary: 'A blockchain gaming platform where the games are not fun but the items are valuable. Players play to earn, then earn to play. It is a cycle.',
    category: 'Crypto',
    basePrice: 8,
    volatility: 0.84,
    trend: 0.02,
    icon: '🎮'
  },
  {
    id: 'mana',
    ticker: 'MANA',
    name: 'Decentraland',
    summary: 'A virtual world where you can buy digital land for real money. The land is empty. The neighbors are absent. The prices are astronomical.',
    category: 'Crypto',
    basePrice: 12,
    volatility: 0.86,
    trend: 0.01,
    icon: '🌐'
  },
  {
    id: 'sand',
    ticker: 'SAND',
    name: 'The Sandbox',
    summary: 'A virtual world where brands build experiences. The experiences are mostly empty rooms with logos. Users visit once, for the airdrop, then leave.',
    category: 'Crypto',
    basePrice: 15,
    volatility: 0.85,
    trend: 0.02,
    icon: '🏖️'
  },
  {
    id: 'axs',
    ticker: 'AXS',
    name: 'Axie Infinity',
    summary: 'A game where you breed cartoon creatures to battle. The creatures cost $300 each. The game pays you to play. The economy collapsed in 2022.',
    category: 'Crypto',
    basePrice: 30,
    volatility: 0.89,
    trend: -0.03,
    icon: '🐉'
  },
  {
    id: 'slp',
    ticker: 'SLP',
    name: 'Smooth Love',
    summary: 'The token used to breed creatures in a blockchain game. It has infinite supply and zero utility. It is worth $0.0003. People still buy it.',
    category: 'Crypto',
    basePrice: 1,
    volatility: 0.97,
    trend: -0.04,
    icon: '💕'
  },
  {
    id: 'chz',
    ticker: 'CHZ',
    name: 'Chiliz Fan',
    summary: 'A token for sports fans to vote on team decisions. The votes are non-binding. The teams ignore them. The fans keep buying tokens.',
    category: 'Crypto',
    basePrice: 20,
    volatility: 0.78,
    trend: 0.03,
    icon: '⚽'
  },
  {
    id: 'rly',
    ticker: 'RLY',
    name: 'Rally Creator',
    summary: 'A platform where creators launch their own tokens. Fans buy the tokens to support creators. The tokens do nothing. The creators are grateful.',
    category: 'Crypto',
    basePrice: 10,
    volatility: 0.88,
    trend: 0.01,
    icon: '📣'
  },
  {
    id: 'fwt',
    ticker: 'FWT',
    name: 'Future Wallet',
    summary: 'A crypto wallet that predicts what you will buy and pre-approves the transaction. It is wrong 80% of the time. The 20% is unsettling.',
    category: 'Crypto',
    basePrice: 50,
    volatility: 0.79,
    trend: 0.04,
    icon: '👛'
  },
  {
    id: 'rndr',
    ticker: 'RNDR',
    name: 'Render Network',
    summary: 'A decentralized GPU network that renders 3D art. Artists pay in tokens. GPU owners earn tokens. Everyone is happy except the electric company.',
    category: 'Crypto',
    basePrice: 70,
    volatility: 0.74,
    trend: 0.08,
    icon: '🎨'
  },
  {
    id: 'imx',
    ticker: 'IMX',
    name: 'Immutable X',
    summary: 'A layer-2 for NFTs that promises zero gas fees. The fees are, in fact, not zero. They are "immutably low." Lawyers are reviewing this claim.',
    category: 'Crypto',
    basePrice: 65,
    volatility: 0.77,
    trend: 0.05,
    icon: '♾️'
  },

  // ---------- Food (111-150) ----------
  {
    id: 'taco2',
    ticker: 'TACO',
    name: 'Taco Bell Royale',
    summary: 'A luxury taco chain where each taco costs $90 and is served on a silver platter. The tacos are identical to regular tacos. The platter is the point.',
    category: 'Food',
    basePrice: 85,
    volatility: 0.20,
    trend: 0.06,
    icon: '🌮'
  },
  {
    id: 'pizz',
    ticker: 'PIZZ',
    name: 'Pizza Planet',
    summary: 'Delivers pizza via drone in under 8 minutes. The pizza arrives slightly airborne and very hot. 3% of deliveries land on the roof. The company calls this "rooftop dining."',
    category: 'Food',
    basePrice: 70,
    volatility: 0.25,
    trend: 0.07,
    icon: '🍕'
  },
  {
    id: 'burg',
    ticker: 'BURG',
    name: 'Burger Bot',
    summary: 'A restaurant with no staff, only robots. The robots make burgers perfectly. They also judge your order silently. You can feel it.',
    category: 'Food',
    basePrice: 55,
    volatility: 0.22,
    trend: 0.08,
    icon: '🍔'
  },
  {
    id: 'sush',
    ticker: 'SUSH',
    name: 'Sushi Cyclone',
    summary: 'Sushi arrives on a conveyor belt that moves at 15 mph. You must catch it with chopsticks. Failure means you go hungry. Diners love the challenge.',
    category: 'Food',
    basePrice: 60,
    volatility: 0.28,
    trend: 0.05,
    icon: '🍣'
  },
  {
    id: 'donu',
    ticker: 'DONU',
    name: 'Donut Forge',
    summary: 'Makes donuts so dense they are technically structural. Used in construction in 3 states. Edible, load-bearing, and glazed.',
    category: 'Food',
    basePrice: 40,
    volatility: 0.18,
    trend: 0.06,
    icon: '🍩'
  },
  {
    id: 'cake2',
    ticker: 'CKTW',
    name: 'Cake Tower Co',
    summary: 'Builds cakes up to 14 feet tall for corporate events. The cakes are not eaten. They are photographed and then demolished. The company recycles the frosting.',
    category: 'Food',
    basePrice: 95,
    volatility: 0.24,
    trend: 0.05,
    icon: '🎂'
  },
  {
    id: 'nood',
    ticker: 'NOOD',
    name: 'Noodle Pipeline',
    summary: 'Pipes fresh ramen directly to your kitchen tap. Turn the hot water handle, get broth. Turn the cold, get chilled noodles. Plumbers hate it. Foodies adore it.',
    category: 'Food',
    basePrice: 65,
    volatility: 0.26,
    trend: 0.07,
    icon: '🍜'
  },
  {
    id: 'curry',
    ticker: 'CURR',
    name: 'Curry Express',
    summary: 'A chain that delivers curry in exactly 90 seconds. The curry is pre-made and stored in heated tubes. It tastes fine. Nobody asks questions.',
    category: 'Food',
    basePrice: 50,
    volatility: 0.20,
    trend: 0.06,
    icon: '🍛'
  },
  {
    id: 'bbq',
    ticker: 'BBQ',
    name: 'Smoke Ring BBQ',
    summary: 'Smokes meats for 18 hours using a proprietary blend of woods. The blend is a secret. The smoke can be smelled from 2 miles away. Neighbors are divided.',
    category: 'Food',
    basePrice: 80,
    volatility: 0.22,
    trend: 0.07,
    icon: '🍖'
  },
  {
    id: 'vegg',
    ticker: 'VEGG',
    name: 'Veggie Vault',
    summary: 'A subscription box of ugly vegetables that supermarkets rejected. The vegetables taste the same. The branding makes customers feel virtuous. Margin is 80%.',
    category: 'Food',
    basePrice: 35,
    volatility: 0.16,
    trend: 0.08,
    icon: '🥕'
  },
  {
    id: 'jui',
    ticker: 'JUI',
    name: 'Juice Press Co',
    summary: 'Cold-presses juice from vegetables you have never heard of. Each bottle costs $14 and contains the nutrients of a single carrot. Customers feel purified.',
    category: 'Food',
    basePrice: 45,
    volatility: 0.24,
    trend: 0.05,
    icon: '🥤'
  },
  {
    id: 'komb',
    ticker: 'KOMB',
    name: 'Kombucha Kingdom',
    summary: 'Brews kombucha in vats the size of swimming pools. The SCOBY is 12 years old and has a name. Employees sing to it. The tea is excellent.',
    category: 'Food',
    basePrice: 38,
    volatility: 0.21,
    trend: 0.06,
    icon: '🫖'
  },
  {
    id: 'choc',
    ticker: 'CHOC',
    name: 'Choco Forge',
    summary: 'Tempers chocolate so precisely it can be shaped into tools. Chocolate wrenches, chocolate hammers. They do not work. They are gifts. Sales are steady.',
    category: 'Food',
    basePrice: 55,
    volatility: 0.19,
    trend: 0.05,
    icon: '🍫'
  },
  {
    id: 'hney',
    ticker: 'HNEY',
    name: 'Honey Hive',
    summary: 'Urban beekeeping on skyscraper rooftops. The honey tastes like car exhaust and ambition. It sells for $40 a jar. Bees are thriving.',
    category: 'Food',
    basePrice: 42,
    volatility: 0.23,
    trend: 0.06,
    icon: '🍯'
  },
  {
    id: 'mapl',
    ticker: 'MAPL',
    name: 'Maple Tap Co',
    summary: 'Taps maple trees in the middle of cities. The trees are in parks. The syrup is sold at farmers markets. The squirrels are agitated.',
    category: 'Food',
    basePrice: 48,
    volatility: 0.20,
    trend: 0.05,
    icon: '🍁'
  },
  {
    id: 'pret',
    ticker: 'PRET',
    name: 'Pretzel Twist',
    summary: 'Makes pretzels in the shape of corporate logos. Companies order them for meetings. Employees eat the logo of their employer. It is cathartic.',
    category: 'Food',
    basePrice: 30,
    volatility: 0.17,
    trend: 0.06,
    icon: '🥨'
  },
  {
    id: 'bagl',
    ticker: 'BAGL',
    name: 'Bagel Tunnel',
    summary: 'A drive-through that sells only bagels. The tunnel is 200 feet long. You receive a bagel every 50 feet. You exit with 4 bagels. You did not choose the flavors.',
    category: 'Food',
    basePrice: 28,
    volatility: 0.19,
    trend: 0.05,
    icon: '🥯'
  },
  {
    id: 'panc',
    ticker: 'PANC',
    name: 'Pancake Stack',
    summary: 'Sells pancakes stacked 12 high. You are not allowed to unstack them. You eat from the top down. The structural integrity is impressive.',
    category: 'Food',
    basePrice: 32,
    volatility: 0.18,
    trend: 0.04,
    icon: '🥞'
  },
  {
    id: 'waff',
    ticker: 'WAFF',
    name: 'Waffle Iron Works',
    summary: 'Makes custom waffle irons that imprint your face onto the waffle. The waffles look like you, slightly distorted. Breakfast becomes introspective.',
    category: 'Food',
    basePrice: 60,
    volatility: 0.22,
    trend: 0.06,
    icon: '🧇'
  },
  {
    id: 'eggs',
    ticker: 'EGGS',
    name: 'Eggcellent Farms',
    summary: 'Chickens that lay eggs with yolks in custom colors. Blue, green, and on request, a deep melancholic purple. The chickens are treated very well.',
    category: 'Food',
    basePrice: 38,
    volatility: 0.20,
    trend: 0.07,
    icon: '🥚'
  },
  {
    id: 'butr',
    ticker: 'BUTR',
    name: 'Butter Churn',
    summary: 'Hand-churns butter in small batches. Each batch is churned by a different person. The butter tastes like the person\'s mood. Optimists\' butter is best.',
    category: 'Food',
    basePrice: 45,
    volatility: 0.19,
    trend: 0.05,
    icon: '🧈'
  },
  {
    id: 'chee',
    ticker: 'CHEE',
    name: 'Cheese Cave',
    summary: 'Ages cheese in underground caves for 5 years. The cheese develops a personality. Some wheels are friendly. Some are hostile. All are expensive.',
    category: 'Food',
    basePrice: 75,
    volatility: 0.21,
    trend: 0.06,
    icon: '🧀'
  },
  {
    id: 'milk',
    ticker: 'MILK',
    name: 'Milk Man Co',
    summary: 'Delivers milk in glass bottles to your door at 5 AM. The milk is from a single cow named Daisy. Daisy is overworked but unionized.',
    category: 'Food',
    basePrice: 35,
    volatility: 0.17,
    trend: 0.04,
    icon: '🥛'
  },
  {
    id: 'yogt',
    ticker: 'YOGT',
    name: 'Yogurt Sphere',
    summary: 'Sells yogurt in spherical containers that roll. The containers are unstable. The yogurt is delicious. The mess is significant.',
    category: 'Food',
    basePrice: 30,
    volatility: 0.20,
    trend: 0.05,
    icon: '🍶'
  },
  {
    id: 'ice',
    ticker: 'ICE',
    name: 'Ice Cream Lab',
    summary: 'Makes ice cream with liquid nitrogen. The ice cream forms in 3 seconds. The fog is dramatic. The flavor is, somehow, always vanilla.',
    category: 'Food',
    basePrice: 42,
    volatility: 0.23,
    trend: 0.06,
    icon: '🍦'
  },
  {
    id: 'cake3',
    ticker: 'CUPK',
    name: 'Cupcake Tower',
    summary: 'A bakery that only sells cupcakes. Each cupcake is a tiny replica of a famous building. The Eiffel Tower is chocolate. The Pyramids are lemon.',
    category: 'Food',
    basePrice: 38,
    volatility: 0.19,
    trend: 0.05,
    icon: '🧁'
  },
  {
    id: 'pops',
    ticker: 'POPS',
    name: 'Popsicle Stick',
    summary: 'Makes popsicles with jokes on the sticks. The jokes are written by an AI. They are not funny. Children memorize them anyway.',
    category: 'Food',
    basePrice: 22,
    volatility: 0.18,
    trend: 0.04,
    icon: '🍭'
  },
  {
    id: 'cand',
    ticker: 'CAND',
    name: 'Candy Crusher',
    summary: 'A candy factory that crushes candy into powder, then reconstitutes it into new candy. The process is infinite. Nothing is ever truly lost.',
    category: 'Food',
    basePrice: 40,
    volatility: 0.22,
    trend: 0.05,
    icon: '🍬'
  },
  {
    id: 'salt',
    ticker: 'SALT',
    name: 'Salt Mine Co',
    summary: 'Mines pink salt from a single mountain. The salt is pink because of minerals. The marketing says it is because of "love." It is minerals.',
    category: 'Food',
    basePrice: 55,
    volatility: 0.16,
    trend: 0.04,
    icon: '🧂'
  },
  {
    id: 'pepp',
    ticker: 'PEPP',
    name: 'Pepper Grinder',
    summary: 'Grows 200 varieties of peppers. The hottest one causes hallucinations. It is legal. The company sells it with a waiver. Buyers sign eagerly.',
    category: 'Food',
    basePrice: 48,
    volatility: 0.24,
    trend: 0.06,
    icon: '🌶️'
  },
  {
    id: 'oliv',
    ticker: 'OLIV',
    name: 'Olive Grove',
    summary: 'Presses olive oil from trees that are 1,000 years old. The oil is thick and peppery. A 375ml bottle costs $60. It is worth it.',
    category: 'Food',
    basePrice: 65,
    volatility: 0.18,
    trend: 0.05,
    icon: '🫒'
  },
  {
    id: 'corn',
    ticker: 'CORN',
    name: 'Corn Maze Co',
    summary: 'Plants corn mazes so complex that 4% of visitors are never found. They are fine. They started new lives in the center. The corn is harvested eventually.',
    category: 'Food',
    basePrice: 35,
    volatility: 0.20,
    trend: 0.04,
    icon: '🌽'
  },
  {
    id: 'mush',
    ticker: 'MUSH',
    name: 'Mushroom Forager',
    summary: 'Forages wild mushrooms from forests. 99% are safe. 1% cause temporary fluency in French. The 1% are sold at a premium to ambitious students.',
    category: 'Food',
    basePrice: 50,
    volatility: 0.26,
    trend: 0.07,
    icon: '🍄'
  },
  {
    id: 'tom',
    ticker: 'TOM',
    name: 'Tomato Vine',
    summary: 'Grows tomatoes on vines that climb buildings. The tomatoes are harvested by window washers. The buildings are productive. The tomatoes are sweet.',
    category: 'Food',
    basePrice: 32,
    volatility: 0.19,
    trend: 0.05,
    icon: '🍅'
  },
  {
    id: 'grap',
    ticker: 'GRAP',
    name: 'Grape Vineyard',
    summary: 'Makes wine from grapes grown on a single hill. The hill has a microclimate. The wine tastes like the hill. The hill is named Gerald.',
    category: 'Food',
    basePrice: 90,
    volatility: 0.22,
    trend: 0.06,
    icon: '🍇'
  },
  {
    id: 'appl',
    ticker: 'APPL',
    name: 'Apple Orchard',
    summary: 'Grows 500 varieties of apples. Each variety has a backstory. The "Grandmother\'s Secret" apple tastes like regret and cinnamon. It is the best seller.',
    category: 'Food',
    basePrice: 42,
    volatility: 0.18,
    trend: 0.05,
    icon: '🍎'
  },
  {
    id: 'cher',
    ticker: 'CHER',
    name: 'Cherry Pit',
    summary: 'Sells cherries with the pits already removed, through a proprietary process. The pits are sold separately as "natural jewelry." Both products are profitable.',
    category: 'Food',
    basePrice: 38,
    volatility: 0.20,
    trend: 0.04,
    icon: '🍒'
  },
  {
    id: 'pine',
    ticker: 'PINE',
    name: 'Pineapple Crown',
    summary: 'Grows pineapples in cold climates using heated greenhouses. The pineapples are confused but delicious. They cost $25 each. People buy them as gifts.',
    category: 'Food',
    basePrice: 55,
    volatility: 0.23,
    trend: 0.05,
    icon: '🍍'
  },
  {
    id: 'mang',
    ticker: 'MANG',
    name: 'Mango Grove',
    summary: 'Imports mangoes from a single orchard in a country no one can find on a map. The mangoes are the best anyone has ever tasted. The orchard is a secret.',
    category: 'Food',
    basePrice: 48,
    volatility: 0.21,
    trend: 0.06,
    icon: '🥭'
  },
  {
    id: 'coco',
    ticker: 'COCO',
    name: 'Coconut Drop',
    summary: 'Harvests coconuts by training monkeys to climb trees. The monkeys are paid in bananas. The coconuts are premium. Animal rights groups are conflicted.',
    category: 'Food',
    basePrice: 40,
    volatility: 0.22,
    trend: 0.04,
    icon: '🥥'
  },
  {
    id: 'avoc2',
    ticker: 'AVCA',
    name: 'Avocado Air',
    summary: 'Flies avocados by drone from orchard to store in 2 hours. The avocados are perfectly ripe on arrival. 5% are dropped on pedestrians. Lawsuits are ongoing.',
    category: 'Food',
    basePrice: 52,
    volatility: 0.25,
    trend: 0.06,
    icon: '🥑'
  },

  // ---------- Space (151-180) ----------
  {
    id: 'star',
    ticker: 'STAR',
    name: 'StarLink Global',
    summary: 'Beams internet from 4,000 satellites. The satellites are visible from Earth and ruin every astronomer\'s photo. Astronomers are furious. Internet users are delighted.',
    category: 'Space',
    basePrice: 220,
    volatility: 0.40,
    trend: 0.10,
    icon: '⭐'
  },
  {
    id: 'moon',
    ticker: 'MOON',
    name: 'Moon Express',
    summary: 'Plans to mine the moon for helium-3. Has not mined anything yet. Has raised $500 million. The moon is unimpressed.',
    category: 'Space',
    basePrice: 95,
    volatility: 0.55,
    trend: 0.06,
    icon: '🌕'
  },
  {
    id: 'mars',
    ticker: 'MARS',
    name: 'Mars Colony Co',
    summary: 'Plans to send 1 million people to Mars by 2050. Has sent 0 people so far. The waiting list has 800,000 names. None of them have been told the fare.',
    category: 'Space',
    basePrice: 180,
    volatility: 0.50,
    trend: 0.08,
    icon: '🔴'
  },
  {
    id: 'rckt',
    ticker: 'RCKT',
    name: 'Reusable Rocket Co',
    summary: 'Lands rockets on drone ships in the ocean. The landings are perfect 60% of the time. The other 40% are "rapid unscheduled disassemblies."',
    category: 'Space',
    basePrice: 250,
    volatility: 0.45,
    trend: 0.09,
    icon: '🚀'
  },
  {
    id: 'satt',
    ticker: 'SATT',
    name: 'Satellite Swarm',
    summary: 'Operates 200 small satellites the size of toasters. They photograph the Earth 24/7. The images are sold to farmers, insurers, and one suspicious government.',
    category: 'Space',
    basePrice: 130,
    volatility: 0.38,
    trend: 0.07,
    icon: '🛰️'
  },
  {
    id: 'tele',
    ticker: 'TELE',
    name: 'Telescope Array',
    summary: 'Operates a radio telescope the size of a city. Listens for alien signals. Has heard nothing in 40 years. The team is optimistic. The budget is generous.',
    category: 'Space',
    basePrice: 85,
    volatility: 0.30,
    trend: 0.04,
    icon: '📡'
  },
  {
    id: 'orb2',
    ticker: 'ORB',
    name: 'Orbital Hotel',
    summary: 'Plans to open a hotel in low Earth orbit. Rooms are $5 million per night. The waiting list is full. The hotel does not exist yet.',
    category: 'Space',
    basePrice: 300,
    volatility: 0.48,
    trend: 0.07,
    icon: '🏨'
  },
  {
    id: 'astd',
    ticker: 'ASTD',
    name: 'Asteroid Miner',
    summary: 'Plans to capture a single asteroid worth $700 quintillion in platinum. Has captured zero asteroids. The stock trades on pure hope.',
    category: 'Space',
    basePrice: 60,
    volatility: 0.65,
    trend: 0.03,
    icon: '☄️'
  },
  {
    id: 'comt',
    ticker: 'COMT',
    name: 'Comet Chaser',
    summary: 'Sends probes to intercept comets and collect dust. The dust is older than the solar system. It is kept in a vault. Scientists weep when they see it.',
    category: 'Space',
    basePrice: 110,
    volatility: 0.35,
    trend: 0.05,
    icon: '🌠'
  },
  {
    id: 'plut',
    ticker: 'PLUT',
    name: 'Pluto Mission',
    summary: 'Wants to reclassify Pluto as a planet by lobbying the IAU. Has spent $20 million on the campaign. Pluto is still a dwarf planet. The CEO is undeterred.',
    category: 'Space',
    basePrice: 40,
    volatility: 0.50,
    trend: 0.02,
    icon: '🪐'
  },
  {
    id: 'jupt',
    ticker: 'JUPT',
    name: 'Jupiter Probe',
    summary: 'Built a probe to study Jupiter\'s Great Red Spot. The spot is shrinking. The probe is en route. It will arrive in 9 years. Patience is required.',
    category: 'Space',
    basePrice: 145,
    volatility: 0.32,
    trend: 0.04,
    icon: '🟠'
  },
  {
    id: 'satn',
    ticker: 'SATN',
    name: 'Saturn Ring Co',
    summary: 'Plans to mine Saturn\'s rings for ice. The ice would be pure water for space colonies. The physics are dubious. The renderings are beautiful.',
    category: 'Space',
    basePrice: 90,
    volatility: 0.52,
    trend: 0.03,
    icon: '🪐'
  },
  {
    id: 'vnu',
    ticker: 'VNU',
    name: 'Venus Hab',
    summary: 'Wants to build floating cities in Venus\'s upper atmosphere, where pressure is Earth-like. The sulfuric acid is a "minor engineering challenge," they say.',
    category: 'Space',
    basePrice: 75,
    volatility: 0.58,
    trend: 0.02,
    icon: '♀️'
  },
  {
    id: 'merc',
    ticker: 'MERC',
    name: 'Mercury Solar',
    summary: 'Plans to build solar panels on Mercury, closest to the sun. The panels would melt. The team is "working on it." The stock is up anyway.',
    category: 'Space',
    basePrice: 55,
    volatility: 0.60,
    trend: 0.01,
    icon: '☀️'
  },
  {
    id: 'deep',
    ticker: 'DEEP',
    name: 'Deep Space Net',
    summary: 'Operates the network that talks to probes beyond the solar system. The signal is faint. The dishes are enormous. The data is slow. It is the only connection.',
    category: 'Space',
    basePrice: 120,
    volatility: 0.28,
    trend: 0.05,
    icon: '🌌'
  },
  {
    id: 'lunr',
    ticker: 'LUNR',
    name: 'Lunar Rover Co',
    summary: 'Builds rovers for the moon. The rovers drive 100 meters per hour. They have found nothing of value. They send beautiful photos. The photos are the value.',
    category: 'Space',
    basePrice: 100,
    volatility: 0.36,
    trend: 0.04,
    icon: '🚙'
  },
  {
    id: 'spac',
    ticker: 'SPAC',
    name: 'Space Suit Tailor',
    summary: 'Makes custom-fitted space suits. Each suit takes 6 months and costs $2 million. The stitching is impeccable. Astronauts refuse to wear anything else.',
    category: 'Space',
    basePrice: 160,
    volatility: 0.30,
    trend: 0.06,
    icon: '👨‍🚀'
  },
  {
    id: 'fuel',
    ticker: 'FUEL',
    name: 'Orbital Fuel Depot',
    summary: 'Operates a gas station in orbit. Satellites refuel and extend their lives. The fuel is expensive. The alternative is building a new satellite. It is cheaper to refuel.',
    category: 'Space',
    basePrice: 140,
    volatility: 0.34,
    trend: 0.07,
    icon: '⛽'
  },
  {
    id: 'dbrs',
    ticker: 'DBRS',
    name: 'Space Debris Clean',
    summary: 'Removes dead satellites from orbit using a giant net. The net is 1 km wide. It has caught 12 objects. The sky is slightly clearer. Progress is slow.',
    category: 'Space',
    basePrice: 85,
    volatility: 0.40,
    trend: 0.05,
    icon: '🧹'
  },
  {
    id: 'grav',
    ticker: 'GRAV',
    name: 'Gravity Research',
    summary: 'Studies artificial gravity for long space flights. Has built a centrifuge that makes astronauts dizzy. No gravity has been created. The research continues.',
    category: 'Space',
    basePrice: 70,
    volatility: 0.42,
    trend: 0.03,
    icon: '🌀'
  },
  {
    id: 'cosm',
    ticker: 'COSM',
    name: 'Cosmic Ray Shield',
    summary: 'Develops shielding for cosmic radiation. The shielding is 2 meters of water. Ships would need to be flying aquariums. NASA is intrigued. Engineers are skeptical.',
    category: 'Space',
    basePrice: 95,
    volatility: 0.38,
    trend: 0.04,
    icon: '🛡️'
  },
  {
    id: 'nav',
    ticker: 'NAV',
    name: 'Star Nav Co',
    summary: 'Builds star trackers that orient spacecraft by the stars. The trackers are accurate to 1 arcsecond. They have never failed. NASA trusts them completely.',
    category: 'Space',
    basePrice: 115,
    volatility: 0.22,
    trend: 0.06,
    icon: '🧭'
  },
  {
    id: 'hthm',
    ticker: 'HTHM',
    name: 'Heliomonitor',
    summary: 'Monitors solar flares that could knock out power grids. Warns Earth 30 minutes before impact. The 30 minutes are used to panic productively.',
    category: 'Space',
    basePrice: 80,
    volatility: 0.30,
    trend: 0.05,
    icon: '🌞'
  },
  {
    id: 'plnt',
    ticker: 'PLNT',
    name: 'Exoplanet Watch',
    summary: 'Operates a telescope that finds planets around other stars. Has found 4,000. None are habitable. The search continues. The data is beautiful.',
    category: 'Space',
    basePrice: 105,
    volatility: 0.33,
    trend: 0.04,
    icon: '🔭'
  },
  {
    id: 'comm',
    ticker: 'COMM',
    name: 'Deep Space Comm',
    summary: 'Builds lasers to communicate with probes at the edge of the solar system. Data rate: 1 bit per second. It is the fastest connection available.',
    category: 'Space',
    basePrice: 90,
    volatility: 0.35,
    trend: 0.05,
    icon: '💡'
  },
  {
    id: 'minr',
    ticker: 'MINR',
    name: 'Lunar Miner',
    summary: 'Plans to mine the moon\'s south pole for water ice. The ice would fuel rockets. The moon has not agreed to this. The company is proceeding anyway.',
    category: 'Space',
    basePrice: 125,
    volatility: 0.48,
    trend: 0.06,
    icon: '⛏️'
  },
  {
    id: 'colny',
    ticker: 'COLNY',
    name: 'Colony Dome Co',
    summary: 'Designs inflatable domes for Mars colonies. The domes are 50 meters across. They have not been tested on Mars. They have been tested in a desert. They leaked.',
    category: 'Space',
    basePrice: 135,
    volatility: 0.44,
    trend: 0.05,
    icon: '⛺'
  },
  {
    id: 'aln',
    ticker: 'ALN',
    name: 'Alien Signal Co',
    summary: 'A company that sells "alien signal detection" subscriptions. No aliens have been detected. Subscribers receive a monthly email saying "still nothing." Retention is 95%.',
    category: 'Space',
    basePrice: 50,
    volatility: 0.55,
    trend: 0.02,
    icon: '👽'
  },
  {
    id: 'wrm',
    ticker: 'WRM',
    name: 'Wormhole Research',
    summary: 'Attempts to create a wormhole in a lab. Has not created a wormhole. Has created a very small, very confused magnetic field. The team is excited.',
    category: 'Space',
    basePrice: 65,
    volatility: 0.62,
    trend: 0.01,
    icon: '🕳️'
  },
  {
    id: 'warp',
    ticker: 'WARP',
    name: 'Warp Drive Labs',
    summary: 'Claims to have invented a warp drive. The drive does not work. The patent is pending. The stock has tripled. Physicists are writing angry letters.',
    category: 'Space',
    basePrice: 110,
    volatility: 0.70,
    trend: 0.03,
    icon: '💫'
  },

  // ---------- Green (181-200) ----------
  {
    id: 'solr',
    ticker: 'SOLR',
    name: 'Solar Panel Peak',
    summary: 'Installs solar panels on every surface, including north-facing walls. The north panels generate nothing. The company calls this "future-proofing."',
    category: 'Green',
    basePrice: 120,
    volatility: 0.25,
    trend: 0.08,
    icon: '☀️'
  },
  {
    id: 'wind',
    ticker: 'WIND',
    name: 'Wind Turbine Co',
    summary: 'Builds wind turbines 300 meters tall. The tips of the blades move at 200 mph. They are visible from space. Birds have learned to avoid them.',
    category: 'Green',
    basePrice: 95,
    volatility: 0.22,
    trend: 0.07,
    icon: '🌬️'
  },
  {
    id: 'hydr',
    ticker: 'HYDR',
    name: 'Hydro Dam Co',
    summary: 'Operates dams that generate power from rivers. The dams also block fish migration. The company installs fish ladders. The fish ignore the ladders. The dams remain.',
    category: 'Green',
    basePrice: 110,
    volatility: 0.18,
    trend: 0.05,
    icon: '💧'
  },
  {
    id: 'geot',
    ticker: 'GEOT',
    name: 'Geothermal Deep',
    summary: 'Drills 5 km into the Earth to access heat. The heat is endless. The drilling is expensive. One well costs $20 million. It powers a small town for 50 years.',
    category: 'Green',
    basePrice: 85,
    volatility: 0.24,
    trend: 0.06,
    icon: '🌋'
  },
  {
    id: 'tidl',
    ticker: 'TIDL',
    name: 'Tidal Generator',
    summary: 'Places turbines on the ocean floor to capture tidal energy. The turbines work. The maintenance is done by robots. The robots are occasionally eaten by sharks.',
    category: 'Green',
    basePrice: 70,
    volatility: 0.28,
    trend: 0.05,
    icon: '🌊'
  },
  {
    id: 'biom',
    ticker: 'BIOM',
    name: 'Biomass Burner',
    summary: 'Burns agricultural waste to generate power. The smoke smells like burning corn. Nearby towns complain. The power is cheap. The compromise is ongoing.',
    category: 'Green',
    basePrice: 55,
    volatility: 0.22,
    trend: 0.04,
    icon: '🔥'
  },
  {
    id: 'batt',
    ticker: 'BATT',
    name: 'Battery Wall Co',
    summary: 'Builds battery walls the size of buildings. They store solar power for the night. The batteries are heavy. The buildings are reinforced. The lights stay on.',
    category: 'Green',
    basePrice: 150,
    volatility: 0.30,
    trend: 0.09,
    icon: '🔋'
  },
  {
    id: 'grid',
    ticker: 'GRID',
    name: 'Smart Grid Co',
    summary: 'Upgrades power grids to be "smart." The grid now sends you passive-aggressive texts when you use too much electricity. Usage is down 12%. Annoyance is up 200%.',
    category: 'Green',
    basePrice: 100,
    volatility: 0.20,
    trend: 0.07,
    icon: '⚡'
  },
  {
    id: 'recy',
    ticker: 'RECY',
    name: 'Recycle Bot',
    summary: 'Robots that sort recycling. They are 99% accurate. The 1% error rate results in glass in the paper bin. The robots do not care. They are robots.',
    category: 'Green',
    basePrice: 65,
    volatility: 0.24,
    trend: 0.06,
    icon: '♻️'
  },
  {
    id: 'cmpt',
    ticker: 'CMPT',
    name: 'Compost King',
    summary: 'Collects food waste from restaurants and composts it. The compost is sold to farms. The farms grow food. The food goes to restaurants. The cycle is complete.',
    category: 'Green',
    basePrice: 45,
    volatility: 0.19,
    trend: 0.05,
    icon: '🌱'
  },
  {
    id: 'tree',
    ticker: 'TREE',
    name: 'Tree Plant Co',
    summary: 'Plants trees for corporations to offset emissions. Each tree costs $5 to plant and offsets 1 ton of carbon over 40 years. The corporations feel better immediately.',
    category: 'Green',
    basePrice: 40,
    volatility: 0.21,
    trend: 0.06,
    icon: '🌳'
  },
  {
    id: 'ocean',
    ticker: 'OCEN',
    name: 'Ocean Clean Co',
    summary: 'Removes plastic from the ocean using giant floating nets. The nets collect plastic and fish. The fish are returned. The plastic is recycled into sunglasses.',
    category: 'Green',
    basePrice: 75,
    volatility: 0.26,
    trend: 0.07,
    icon: '🌊'
  },
  {
    id: 'coral',
    ticker: 'CORAL',
    name: 'Coral Restore',
    summary: 'Grows coral in labs and transplants it to dying reefs. The coral grows 10x faster than wild coral. The reefs are recovering. The fish are returning. It works.',
    category: 'Green',
    basePrice: 60,
    volatility: 0.23,
    trend: 0.08,
    icon: '🪸'
  },
  {
    id: 'bees',
    ticker: 'BEES',
    name: 'Bee Sanctuary',
    summary: 'Maintains 10,000 beehives on corporate rooftops. The bees pollinate the city. The honey is sold. The corporations get a tax break. The bees are the real winners.',
    category: 'Green',
    basePrice: 50,
    volatility: 0.20,
    trend: 0.06,
    icon: '🐝'
  },
  {
    id: 'moss2',
    ticker: 'MWAL',
    name: 'Moss Wall Co',
    summary: 'Installs living moss walls in offices. The moss cleans the air. The walls need misting. The misting is automated. The offices smell like a forest after rain.',
    category: 'Green',
    basePrice: 55,
    volatility: 0.18,
    trend: 0.05,
    icon: '🌿'
  },
  {
    id: 'alg',
    ticker: 'ALG',
    name: 'Algae Biofuel',
    summary: 'Grows algae in transparent tubes to produce biofuel. The algae grows fast. The fuel is carbon-negative. The process is expensive. The future is green.',
    category: 'Green',
    basePrice: 80,
    volatility: 0.32,
    trend: 0.07,
    icon: '🟢'
  },
  {
    id: 'h2',
    ticker: 'H2',
    name: 'Hydrogen Fuel Co',
    summary: 'Produces hydrogen from water using solar power. The hydrogen fuels cars and buses. The only emission is water. The cars are expensive. The buses are coming.',
    category: 'Green',
    basePrice: 90,
    volatility: 0.28,
    trend: 0.08,
    icon: '💨'
  },
  {
    id: 'carb',
    ticker: 'CARB',
    name: 'Carbon Capture',
    summary: 'Builds machines that suck CO2 from the air. The machines are the size of buildings. They capture 1 ton per day. The world emits 100 million tons per day. It is a start.',
    category: 'Green',
    basePrice: 130,
    volatility: 0.35,
    trend: 0.06,
    icon: '🏭'
  },
  {
    id: 'insl',
    ticker: 'INSL',
    name: 'Insulation Pro',
    summary: 'Makes insulation from recycled denim. Old jeans become home insulation. Houses are warmer. Jeans are reborn. The company has diverted 10 million pairs from landfills.',
    category: 'Green',
    basePrice: 48,
    volatility: 0.17,
    trend: 0.05,
    icon: '🧵'
  },
  {
    id: 'rain',
    ticker: 'RAIN',
    name: 'Rainwater Co',
    summary: 'Installs rainwater collection systems on homes. The water is used for gardens and toilets. The systems pay for themselves in 3 years. The gardens are lush.',
    category: 'Green',
    basePrice: 42,
    volatility: 0.19,
    trend: 0.06,
    icon: '🌧️'
  }
];
